### ISSUE TITLE
AEM 6.0 SP2: ACS Common Multifield: the ‘loadcontent’ event does not fire for the widgets even when placed in a multifield when authored for second time

### ISSUE THREAD

**Issue by rgummalla** [Adobe-Consulting-Services/acs-aem-commons#519] opened 2015-08-28 23:24 UTC
On AEM 6.0 SP2, customer reported the issue as mentioned below

1.Create a component with dialog with multifield
2.Add ACS Commons multifield in the dialog
3.In the multifield, add listener to loadcontent event for the widget in multifield.
4.Author the component once. The listener fires as expected.
5.Edit the component again.
6.The listener for Loadcontent does not get fired as expected.

**Comment by rgummalla** [comment] 2015-08-28 23:26
This is a blocker in our current release 1.15. Wherec ustomer was not able to move few complex components for testing, with this issue. Also, They are in their last sprint and if they don’t close on this at the earliest, it would impact our timeline

**Comment by justinedelson** [comment] 2015-08-29 10:16
Can you attach a sample component which can be used to reproduce this issue?

**Comment by rgummalla** [comment] 2015-08-31 22:51
A JIRA https://jira.corp.adobe.com/browse/CQ-52842 opened contains the sample component

**Comment by justinedelson** [comment] 2015-09-01 02:57
Please post the package here.

**Comment by rgummalla** [comment] 2015-09-01 03:08
Well i tried uploading here. i am getting "Unfortunately, we don’t support that file type." its not working. please download from the link below

https://app.box.com/s/4iy3iog2k5nxcwyvt010renahithb50l

**Comment by justinedelson** [comment] 2015-09-01 03:41
Sorry, I meant please post a public link to the package here. Looks like the box link will work.

**Comment by rgummalla** [comment] 2015-09-01 21:43
Hi Justin,

Thanks for looking into this. Do you have any lead on the root cause for this issue. I am having a weekly synch up with customer. Appreciate if you can provide any update.

**Comment by justinedelson** [comment] 2015-09-01 21:44
If there is a time sensitivity, I'd suggest having the customizer try to create a patch. I don't forsee having a chance to dig into this in the next week or so.

**Comment by rgummalla** [comment] 2015-09-04 16:18
Issue 1:
Issue: When there is a dropdown inside a multifield, the second time we open the dialog, the dropdown field gets shrink, even if data is present.
Summary: This is related to a component with multifield in its dialog. When there is a dropdown inside a multifield, the second time we open the dialog, the dropdown field gets shrink, even if data is present.
How to reproduce: 
Step 1: Drag and drop a component with dropdown inside a multifield.
Step 2: Click and edit the component and click on OK.
Step 3: Click on edit again and try to modify the component.
Step 4: The dropdown field size is reduced. (Requirement field)
Occurrence: It occurs always for a multifield
Business Impact: Authoring is difficult as the data that is authored previously is not visible.

Issue 2:
Issue: When there is a pathfield inside a multifield, the second time we try to author the pathfield without clicking on OK, drag and drop functionality is not working.
Summary: This is related to a component with multifield in its dialog. When there is a pathfield inside a multifield, the second time we try to author the pathfield without clicking on OK, drag and drop functionality is not working.
How to reproduce: 
Step 1: Drag and drop a component with pathfield inside a multifield.
Step 2: Click and edit the component.
Step 3: Click on Add Item and drag and drop an image in the pathfield.
Step 4: Delete the item in the multifield, by clicking on the red delete icon.
Step 5: Now without click OK, click on Add Item again and try to drag and drop image into the same pathfield
Step 6: Drag and drop functionality doesn’t work. (Image field)
Occurrence: It occurs always for a multifield
Business Impact: Authoring is difficult as the drag and drop functionality is not working. Author might have to browse to the image in folder structure to configure it.

**Comment by schoudry** [comment] 2015-09-06 22:33
Ram, the package is too project-specific with following nodes missing (feeding the dropdowns)(https://app.box.com/s/4iy3iog2k5nxcwyvt010renahithb50l)

/etc/commerce/products/intelsecurity/catalog
/consumer/services/promotionservlet
/consumer/services/productcomparisionservlet
/etc/designs/intelsecurity/assets

can the developer create&upload a simple component with only the widget (dropdown) & loadcontent listener in composite multifield, a servlet with static options for the dropdown 
+   
a recording explaining the steps would help ...

**Comment by rgummalla** [comment] 2015-09-08 20:03
Hi Sree, Justin,

This is being escalated by customer. I have requested what sree had recommended in this earlier post.

Please let us know the next steps

Thanks
ram

**Comment by schoudry** [comment] 2015-09-08 21:17
Ram, let me know when you have the package and i can investigate ( when i get some free time from UA project work.....)

**Comment by schoudry** [comment] 2015-09-11 20:21
Ram, please update the issue when you have confirmation from Mcafee on the fix.... ill submit a pull request

**Comment by justinedelson** [comment] 2015-09-22 13:25
Fixed with #540

**Comment by davidjgonzalez** [comment] 2015-09-24 20:54
@justinedelson it looks like some commits for this fix may have been missed when cutting the 2.0.6 release. (master vs 2.0.6 ..  multipanel.js is different)

/cc @schoudry anything else missing?

**Comment by justinedelson** [comment] 2015-09-24 21:50
Argh... Take a look at the release/2.0.8 branch. I think I got everything this time.

**Comment by schoudry** [comment] 2015-09-24 22:39
2.0.8 looks fine

**Closed** 2015-09-25 11:49 UTC
Labels: bug
