### ISSUE TITLE
AEM Sites -> Rails -> Content Tree function can't load pages if set page title in Japanese with Aem Environment Indicator

### ISSUE THREAD

**Issue by hitchen5007** [Adobe-Consulting-Services/acs-aem-commons#2473] opened 2020-11-10 05:20 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6
* [ ] ACS AEM Commons Version: 4.8.6
* [ ] Reproducible on Latest? no

### Expected Behavior

Content Tree can load pages.

### Actual Behavior

If Aem Environment Indicator configuration is set, Content Tree can't load page if page title is set to Japanese.
If remove Aem Environment Indicator configuration, it works fine.

### Steps to Reproduce

Config Aem Environment Indicator in AEM Web Console
Create a page under We.Retail website and set page title in Japanese ( example : 日本語テスト）
Aem Start Page -> Sites -> Rails -> select 'Content Tree' -> expand We.Retail 

### Links

None errors but only below message are printed in error.log when refresh sites page,

10.11.2020 14:13:44.005 *WARN* [9.115.24.75 [1604985223993] GET /sites.html/content/we-retail HTTP/1.1] com.adobe.acs.commons.util.BufferedServletResponse Prevent committing the response, it will be committed deferred, i.e. once this buffered response is closed
10.11.2020 14:13:49.786 *INFO* [sling-default-5-health-org.apache.sling.discovery.oak.SynchronizedClocksHealthCheck] org.apache.sling.discovery.oak.SynchronizedClocksHealthCheck execute: no topology connectors connected to local instance.

and we can see an error happened in browser console shown as below.

![範囲を選択_001](https://user-images.githubusercontent.com/58934437/98630872-0fd9f000-2357-11eb-98bd-bed5969e0189.png)

**Comment by kwin** [comment] 2020-11-10 06:09
This is a duplicate of #2425.

**Comment by hitchen5007** [comment] 2020-11-11 02:24
Sorry, which release will fix this?
In the latest version 4.9.2, it still show error in sites page.
![範囲を選択_003](https://user-images.githubusercontent.com/58934437/98757683-065c9080-2408-11eb-9bd9-d23775dfe5e5.png)

**Comment by kwin** [comment] 2020-11-11 08:45
I do no longer see the error `Unexpected end of JSON input` in the console in your new screenshot. Can you debug which response returns which error that leads to the error message `Could not load content`?

**Comment by hitchen5007** [comment] 2020-11-16 08:28
Sorry for late reply,  here is my debug result. 

**1. with Aem Environment Indicator**

![範囲を選択_006](https://user-images.githubusercontent.com/58934437/99227146-cfcaaf80-2825-11eb-8933-d62dfd1495a3.png)

 {"items" : [{}...], "hasmore" : false} was printed twice, so it can't be previewed.

{"items":[{"title":"Campaigns","path":"/content/campaigns","icon":"folder","id":"/content/campaigns","selectable":true,"hasItems":true},{"title":"Core Components","path":"/content/core-components-examples","icon":"experience","id":"/content/core-components-examples","selectable":true,"hasItems":true},{"title":"Community Sites","path":"/content/sites","icon":"folder","id":"/content/sites","selectable":true,"hasItems":true},{"title":"Screens","path":"/content/screens","icon":"folder","id":"/content/screens","selectable":true,"hasItems":true},{"title":"We.Retail","path":"/content/we-retail","icon":"experience","id":"/content/we-retail","selectable":true,"hasItems":true},{"title":"日本語テスト","path":"/content/test","icon":"experience","id":"/content/test","selectable":true,"hasItems":false}],"hasMore":false}
{"items":[{"title":"Campaigns","path":"/content/campaigns","icon":"folder","id":"/content/campaigns","selectable":true,"hasItems":true},{"title":"Core Components","path":"/content/core-components-examples","icon":"experience","id":"/content/core-components-examples","selectable":true,"hasItems":true},{"title":"Community Sites","path":"/content/sites","icon":"folder","id":"/content/sites","selectable":true,"hasItems":true},{"title":"Screens","path":"/content/screens","icon":"folder","id":"/content/screens","selectable":true,"hasItems":true},{"title":"We.Retail","path":"/content/we-retail","icon":"experience","id":"/content/we-retail","selectable":true,"hasItems":true},{"title":"日本語テスト","path":"/content/test","icon":"experience","id":"/content/test","selectable":true,"hasItems":false}],"hasMore":false}

**2. without Aem Environment Indicator**

![範囲を選択_007](https://user-images.githubusercontent.com/58934437/99227987-f9380b00-2826-11eb-8971-7254e1cedcad.png)

Json response is correct this time.

It seems that Json response check is executed in /libs/granite/ui/components/coral/foundation/components/clientlibs/components/build/all.js,  
since I can't read its source, I am not sure about this.
Would you please help check why json response is duplicated  if use  Aem Environment Indicator ?

**Comment by LucaNerlich** [comment] 2020-11-17 13:05
Ive also noticed the duplicate reponsose content here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2477

Although in my case it does work with 4.8.6, just not with 4.9.2. Root cause might be the same / very similar.

**Comment by kwin** [comment] 2020-11-21 19:01
The latter issue (with response body duplicated) is a duplicate of #2475. Please try the PR attached there.

**Closed** 2020-12-11 15:40 UTC
