### ISSUE TITLE
Experience fragment edit mode issue

### ISSUE THREAD

**Issue by salman18j** [Adobe-Consulting-Services/acs-aem-commons#1602] opened 2018-12-03 21:26 UTC
I am not able to add any other component after adding General - Experience Fragment Component on Page. I am getting following JS error on the page after installing ACS commons:

 

An error has occured during execution of the selected action: code.indexOf is not a function -> TypeError: code.indexOf is not a function

    at Object.ns.util.sanitizeCQHandler (http://localhost:4502/libs/cq/gui/components/authoring/editors/clientlibs/sites/page.ffa6f d2f38c3c80c2958f648bf0e8134.js:32855:62)

    at http://localhost:4502/libs/cq/gui/components/authoring/editors/clientlibs/core.62a4d5c9215 9bcf5ed8650762d1c1809.js:7508:46

    at Array.forEach (<anonymous>)

    at cleanActions (http://localhost:4502/libs/cq/gui/components/authoring/editors/clientlibs/core.62a4d5c9215 9bcf5ed8650762d1c1809.js:7491:21)

    at cleanEditableActions (http://localhost:4502/libs/cq/gui/components/authoring/editors/clientlibs/core.62a4d5c9215 9bcf5ed8650762d1c1809.js:7476:38)

    at Object.ns.configParser (http://localhost:4502/libs/cq/gui/components/authoring/editors/clientlibs/core.62a4d5c9215 9bcf5ed8650762d1c1809.js:7664:9)

    at new constructor (http://localhost:4502/libs/cq/gui/components/authoring/editors/clientlibs/core.62a4d5c9215 9bcf5ed8650762d1c1809.js:8822:29)

    at HTMLUnknownElement.<anonymous> (http://localhost:4502/libs/cq/gui/components/authoring/editors/clientlibs/core.62a4d5c9215 9bcf5ed8650762d1c1809.js:35820:36)

    at Function.each (http://localhost:4502/etc.clientlibs/clientlibs/granite/jquery.5e8d3382f82b03b0bf3fea3024e ecd61.js:370:19)

    at jQuery.fn.init.each (http://localhost:4502/etc.clientlibs/clientlibs/granite/jquery.5e8d3382f82b03b0bf3fea3024e ecd61.js:137:17)

**Comment by badvision** [comment] 2018-12-03 21:33
What version of ACS Commons did you install prior to seeing this issue?

**Comment by salman18j** [comment] 2018-12-03 21:38
I was not using experience fragments before. Currently, I am on AEM 6.4.2 and tried with  ACS Commons 3.18.0, 3.18.2 and 3.19.0. all version have this issue.

**Comment by davidjgonzalez** [comment] 2018-12-03 22:33
@salman18j are you using the Versioned Clientlibs?

I your JS is being served with a SPACE in it? http://localhost:4502/libs/cq/gui/components/authoring/editors/clientlibs/core.62a4d5c9215 9bcf5ed8650762d1c1809.js 

(between the 5c9215 and 9bcf5) ... is that correct?

What all are you using in ACS Commons, and w/ what configurations?

**Comment by davidjgonzalez** [comment] 2018-12-03 22:45
Able to reproduce ...
![image](https://user-images.githubusercontent.com/1451868/49406280-24e98580-f723-11e8-87ba-a88872f97402.png)

Looks like the limit parsys is problematic.

**Comment by davidjgonzalez** [comment] 2018-12-04 13:20
So looked into this a bit more - appears to be an issue when `Granite.author.edit.findEditables()` when a General - Experience Fragment component is an editable on the page. (which is why it showed up for multiple tools in the above comment).
You can reproduce this by going to a we.retail page, adding ane experience fragment, and then from the browser JS console executing: `Granite.author.edit.findEditables()`.

Im not sure how to fix this since as getting the parsys editable on the page is a critical piece of these components, and its in the finding of the editable that this breaks. @schoudry  any thoughts?

**Comment by schoudry** [comment] 2018-12-04 22:59
@davidjgonzalez not sure, i have to check

**Comment by schoudry** [comment] 2018-12-06 17:52
![image](https://user-images.githubusercontent.com/6585493/49601707-32358880-f94c-11e8-9c2c-700062344122.png)

@davidjgonzalez not sure if this a problem with jquery itself (automatically converting string into function when data attributes are passed to `$()` ), but i think a better way to handle it is by fixing product code  `Granite.author.util.sanitizeCQHandler` to not always expect code to be `string` and do a check like `if(typeof code == 'function') { return _superSanitizeCQHandler.call(this, code); }`

we could override the function `Granite.author.util.sanitizeCQHandler` or defer to product

**Comment by schoudry** [comment] 2018-12-06 17:55
problem code in /libs/fd/af/components/aemform/authorLib/editListener/javascript/PreviewHook.js

**Comment by kunwarsaluja** [comment] 2018-12-07 16:56
^fixed in 6.4.3 out ~Dec20.  You can request Adobe Support for the interim solution  if you can't upgrade right away

**Comment by schoudry** [comment] 2018-12-07 17:04
yes the following change in product (NPR-26977) should fix it

`if (window.guidelib == null && code != null && typeof code === 'string' &&  (code.indexOf("guidelib") === 0 || (code.indexOf("guidelib.author"))) >= 0) {`

**Comment by schoudry** [comment] 2018-12-07 17:05
@davidjgonzalez @salman18j closing, reopen if necessary

**Closed by schoudry** 2018-12-07 17:05 UTC
Labels: bug

**Comment by davidjgonzalez** [comment] 2018-12-07 17:21
@schoudry is there a way we can disable this by default? Regardless of being a product issue, our (acs commons)'s problem is that it seems to break AEM even if someone isnt USING these features (and didnt explicitly enable them). that is bad!

**Comment by davidjgonzalez** [comment] 2018-12-12 19:56
@schoudry any idea if the monkey patch will be forward compatible (with the productized fix?) and/or the level of risk in breaking other things in current/future releases?

Easier said that done, but i'd personally just like to rip off the band-aid and turn all these authoring clientlibs off by default; then having a monkey patch wouldn't be so bad since that would be the risk youd have to accept for using a single feature, vs requiring a monkey patch to use a product feature with ANY acs commons feature.

**Comment by schoudry** [comment] 2018-12-12 20:06
@davidjgonzalez first thought it'd be an override, so yes it affects current and future.. (we can put conditional band-aids for compatibility but it only makes code more confusing....) i'd like to propose upgrading/patching AEM product as a fix for this issue and not patch ACS commons

and i totally agree, convert the UI clientlibs into feature-enabled is a better way... i'll ping you

**Comment by salman18j** [comment] 2018-12-13 14:10
@schoudry we are planning to upgrade 6.4.3. When it will be available?

**Comment by kunwarsaluja** [comment] 2018-12-13 14:30
@salman18j  The fix is already part of AEM 6.4.3

**Comment by salman18j** [comment] 2018-12-31 19:21
AEM 6.4.3 has another issue. if you install it on top AEM 6.4.2. you can't edit any component.
