### ISSUE TITLE
Email Notification is not working as expected on one set of environment where as working on other set of environment

### ISSUE THREAD

**Issue by KritiRathiTela** [Adobe-Consulting-Services/acs-aem-commons#1137] opened 2017-10-12 12:07 UTC
Email Notification is not working as expected on one set of environment where as working on other set of environment with the same SMTP details.

FYI - There is no password associated with the SMTP which is being used.

Below are the logs from environment where its failing 

at com.day.cq.mailer.impl.DefaultMailService.send(DefaultMailService.java:291)
at com.day.cq.mailer.impl.DefaultMailService.send(DefaultMailService.java:45)
at com.adobe.acs.commons.email.impl.EmailServiceImpl.sendEmail(EmailServiceImpl.java:116)
at com.adobe.acs.commons.email.impl.EmailServiceImpl.sendEmail(EmailServiceImpl.java:87)
..
..
..
Caused by: javax.mail.AuthenticationFailedException: failed to connect, no password specified?
	at javax.mail.Service.connect(Service.java:329)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:253)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1232)
	... 15 common frames omitted

**Comment by davidjgonzalez** [comment] 2017-10-12 12:12
Can you verify that aem can send emails from this system at all? Use the smtp healthcheck that acs commons provides to easily do this.

This does not look like a problem w acs commons but rather a misconfiguration of aem,smtp, or the network between them.

**Comment by KritiRathiTela** [comment] 2017-10-12 12:39
Email can be send from command like from the system.

**Comment by KritiRathiTela** [comment] 2017-10-12 12:41
how to perform smtp healthcheck using acs commons ?
FYI - we are using 2.5.0 version

**Comment by justinedelson** [comment] 2017-10-12 13:30
The SMTP Health Check was added in 2.13.0

See https://adobe-consulting-services.github.io/acs-aem-commons/features/healthchecks/status-emailer/index.html

**Comment by KritiRathiTela** [comment] 2017-10-12 13:38
So, I won't be able to use that. is there any other way it can be checked ?

**Comment by justinedelson** [comment] 2017-10-12 13:40
You can do what the Health Check does in your own code. As @davidjgonzalez notes, the log messages you posted point to a configuration issue at the AEM level, but invoking the mail service directly would confirm that.

**Comment by KritiRathiTela** [comment] 2017-11-06 14:00
Hi there, 

any idea where it set - DEBUG SMTP : useEhlo true, **useAuth true**
Some how its getting useAuth as true because of its failing with given exception given while raising issue.

**Comment by justinedelson** [comment] 2017-11-06 14:07
> any idea where it set - DEBUG SMTP : useEhlo true, useAuth true

This would be set by either manually specifying the credentials in the Email object (unlikely) or specifying a username in the DefaultMailService configuration.

**Comment by KritiRathiTela** [comment] 2017-11-07 04:35
There is no username specified in DefaultMailService hence not able to get where this actually being setting up.

**Comment by justinedelson** [comment] 2017-11-07 13:57
Agreed. Assuming you are able to reproduce this with directly coding against the MailService, it seems to be a product issue. I'd suggest you work with Daycare to resolve.

**Comment by KritiRathiTela** [comment] 2017-11-09 06:14
Sure, will take it from with DayCare. Let's see what they come up with.
Thanks a lot to all :)

**Comment by justinedelson** [comment] 2017-12-13 18:32
Closing as assumed to be product/config issue.

**Closed by justinedelson** 2017-12-13 18:32 UTC
