### ISSUE TITLE
ACS Commons Bundle does not start on AEM as a Cloud Service SDK Quickstart Jar

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2298] opened 2020-05-11 21:14 UTC
It appears there is some incompatibility here. To workaround, update the entry in your `crx-quickstart/conf/sling.properties` file:

`sling.feature.apiregions.default=com.adobe.aem.deprecated`

![image](https://user-images.githubusercontent.com/1451868/81815680-46de5e80-94f8-11ea-94f6-6e38f2831b87.png)

**Comment by stefanseifert** [comment] 2020-05-29 08:53
it seems https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/210d027e0868529d138700822b507c189e42af1f/bundle/src/main/java/com/adobe/acs/commons/indesign/dynamicdeckdynamo/utils/DynamicDeckUtils.java#L221-L245 is the culprit?

i assume the package 'com.day.cq.dam.api.collection' is deprecated and should not be used.

**Comment by stefanseifert** [comment] 2020-05-29 08:56
so it seems to be broken by #2266 (released in 4.6.0)

**Comment by joerghoh** [comment] 2020-05-29 10:16
@stefanseifert imo "deprecated" is different from "breaks the build".

**Comment by badvision** [comment] 2020-05-29 12:01
The general guidance we have on deprecated api features such as binary handling methods is that they will compile (for now) but will error or do nothing if used in as AEM Cloud. Either way those kind of deprecated method calls shouldn't interfere with deployment based on what I've heard.

**Comment by davidjgonzalez** [comment] 2020-05-29 13:00
Looking for its replacement.. i see the package in 6.4 javadocs [1] without any deprecation notice..

But then it goes missing in 6.5 java docs [2]

And is removed entirely from AEM CS Java docs or in the Deprecated API List (which makes sense, since this is the deprecated list for the NON-deprecated AEM-API jar).. and i can't find the javadocs for the API-API Deprecated jar...

I was hoping the Javadocs could tell me what the replacement is, but it seems this packaged was ghosted between 6.4 and 6.5... 

[1] https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/reference-materials/javadoc/com/day/cq/dam/api/collection/SmartCollection.html

[2] https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/reference-
materials/javadoc/index.html

[3]https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/developing/ref/javadoc/overview-summary.html

[4] https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/developing/ref/javadoc/deprecated-list.html

**Comment by badvision** [comment] 2020-05-29 13:03
Oh wow, that sucks. :(  If there is a replacement class then we could provide a wrapper that bridges the gap, as I did for the unexpected change in the shipping version of Apache POI that broke things a few months ago.

**Comment by davidjgonzalez** [comment] 2020-05-29 13:23
Quick and dirty fix since I can't find the recommended replacement API.

https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2319

**Comment by joerghoh** [comment] 2020-05-29 13:51
See GRANITE-29881

**Comment by badvision** [comment] 2020-05-29 14:08
Joerg: GRANITE-22035

**Comment by joerghoh** [comment] 2020-05-29 19:12
ok, just got the report that 4.7.2 is not working on AEMaaCS because of this issue... we definitly have to turn this into a bug in our code now and urge others to follow a proper deprecation policy.

**Comment by davidjgonzalez** [comment] 2020-05-29 23:01
So this isn’t considered part of the deprecated APIs in AEM CS - It’s completely removed? I had assumed it was the former 😞

**Comment by stefanseifert** [comment] 2020-07-09 21:44
i think this is solved with release 4.7.2? i could not reproduce the problem with this release in quickstart SDK jar 2020.6.3800.20200626T210738Z

**Comment by davidjgonzalez** [comment] 2020-07-09 21:58
Fixed via https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2323 in 4.7.2

**Closed** 2020-07-09 21:58 UTC
Labels: pinned, product issue
