### ISSUE TITLE
Redirect Manager - possible to create an entry with empty source and/or target paths

### ISSUE THREAD

**Issue by danijelbasic** [Adobe-Consulting-Services/acs-aem-commons#2831] opened 2022-04-28 11:38 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: Adobe Experience Manager (6.5.11.0)
* [ ] ACS AEM Commons Version: 5.0.10
* [ ] Reproducible on Latest? yes

### Expected Behavior

When a new redirect entry is created, source and target paths should not be empty. The redirect entry creation dialog should prevent it.

### Actual Behavior

It is possible to create a redirect entry, even though Source Path and Target Path fields are marked as mandatory.

### Steps to Reproduce

1) open ACS Commons Redirect Manager: Tools > ACS Commons > Manage Redirects
2) open one of the existing configurations or create a new one
3) click on Redirect Configuration button. The redirect entry creation dialog appears.
4) without setting Source Path and Target Path fields, try to save the entry 

### Links

None

### Additional info

My assumption is that the handler attached on Save button (the one that submits the redirect entry creation dialog) does not do any validation.
Source code: /apps/acs-commons/components/utilities/manage-redirects/clientlibs/app.js, line 63
`$(document).on("click", ".cq-dialog-submit", function (e) {
  // ...
})`

**Comment by danijelbasic** [comment] 2022-04-28 14:36
Hi Yegor,

I can reproduce it on Firefox, Safari and Chrome. Btw, I use MacBook Pro (macOS 12.2.1).

<img width="1027" alt="Screenshot 2022-04-28 at 16 30 27" src="https://user-images.githubusercontent.com/20317080/165777218-b1f2b942-b4cd-4b3e-be66-73446cc03228.png">

**Comment by YegorKozlov** [comment] 2022-04-28 16:08
@danijelbasic Can you please check with the latest v5.3.0 ? Things might have changed since v5.0.10.

**Comment by davidjgonzalez** [comment] 2022-05-02 18:28
Closing - I tested this on 5.3.0 and cannot reproduce on Chrome, FF or Safari (macOS as well).

**Closed by davidjgonzalez** 2022-05-02 18:28 UTC
Labels: need more info
