### ISSUE TITLE
ComponentErrorHandlerImpl has unsatisfied reference in 4.0.0 with AEM 6.5

### ISSUE THREAD

**Issue by maurerstefan** [Adobe-Consulting-Services/acs-aem-commons#1845] opened 2019-04-18 08:21 UTC
## Required Information

* AEM Version: 6.5.0
* ACS AEM Commons Version: 4.0.0

### Expected Behavior

ComponentErrorHandlerImpl  should be running and added in the filter chain.

### Actual Behavior

ComponentErrorHandlerImpl has unsatified reference to ModeUtil and isn't active.

![image](https://user-images.githubusercontent.com/2833634/56346961-8a667c00-61c3-11e9-9d04-a19da682091b.png)

### Links

http://disq.us/p/205zkxn
https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/59b165575017da39b61a317d89bb303571149bbc#diff-dc70accb13cbcced9d11c4b1914cf54e

**Comment by tml** [comment] 2019-04-18 16:35
I am unable to reproduce this in a vanilla instance of AEM 6.5 with AEM Commons 4.0.0 - the ModeUtil component registers correctly for me, resulting in this dependency being resolved:


![image](https://user-images.githubusercontent.com/35148/56376612-90f5f300-61c5-11e9-8d9d-d976d2cc12db.png)

![image](https://user-images.githubusercontent.com/35148/56376648-aa973a80-61c5-11e9-8d60-af69d2fbf3e4.png)

**Comment by davidjgonzalez** [comment] 2019-04-19 16:59
@maurerstefan does this consistently break for you?

@bstopp IIRC you made the ModeUtil, which works in a slightly off manner (its has static methods that access OSGI state IIRC?) Thoughts on why this might be happening?

**Comment by bstopp** [comment] 2019-04-19 17:15
Well, it has static methods that check the state against the request/current system. The only time it accesses the OSGi is at Component _configuration_ time, as those Runmodes can only be set then. It also is _immediate_ so, this should never be unsatisfied (as `ModeUtils` has no dependencies).

**Comment by maurerstefan** [comment] 2019-04-23 08:52
Yes, it consistently break for me.

I've now tried with a vanilla AEM 6.5 instance. After installing ACS Commons 4.0.0, the component is in state **no config**:
![image](https://user-images.githubusercontent.com/2833634/56567394-19550900-65b5-11e9-9299-9b06c7de8e1c.png)

And the Servlet Filter `ComponentErrorHandlerImpl` is not in registered/used:
![image](https://user-images.githubusercontent.com/2833634/56567421-2b36ac00-65b5-11e9-9518-c66eef87a2b4.png)

After I configure the `ComponentErrorHandlerImpl` directly via /system/console/configMgr (just leave the default values) and click Save, the component state changes to **unsatisfied (reference)**:
![image](https://user-images.githubusercontent.com/2833634/56567604-94b6ba80-65b5-11e9-8af0-d2ab3d78d2dc.png)

The Component `ModeUtil` is always in state **active**.

**Comment by davidjgonzalez** [comment] 2019-04-23 12:56
Confirmed this is a bug in 4.0.0.

@badvision why was this updated to be a @Reference in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1568 ? It looks like it was part of some mass update - was this intentional?

@bstopp ModeUtil is not an OSGi Service, so this wouldn't work/it's not how it's intended to be used right? Am I missing something?

**Comment by bstopp** [comment] 2019-04-23 16:06
@davidjgonzalez That is correct. This is a component, but not a service. There's no reason to inject it as it is a true _utility_. No state, no configuration, just helper methods. (And now that i think about it, probably doesn't need the `@ProviderType`? )

So I can see why it'd fail - there is no service registered.

**Comment by badvision** [comment] 2019-04-23 18:55
I believe I did some refactoring around that to clean things up but might have done that by accident.  I'll have a look.

**Comment by maurerstefan** [comment] 2019-05-07 09:08
Thank you @badvision for fixing this.

Is there already a schedule for the next release?

**Comment by badvision** [comment] 2019-05-07 11:55
A new release is eminent but I have a stack of pull requests of other fixes that need review.  I might just cut a release this week and let those other PR's go to the next release.

**Comment by maurerstefan** [comment] 2019-05-09 09:10
Looks like this hasn't been fixed after all.

ModeUtil is still used like a service in `ComponentErrorHandlerImpl.java`
```java
@Reference
private ModeUtil modeHelper;
```

but isn't one:
```java
@ProviderType
@Component(immediate = true)
@SuppressWarnings("squid:S1118")
public final class ModeUtil {
```

Therefore it's still unsatisfied:
![image](https://user-images.githubusercontent.com/2833634/57441844-0d22aa00-724b-11e9-9ef0-0b53565a940f.png)

**Comment by davidjgonzalez** [comment] 2019-05-10 00:23
@maurerstefan sorry about this - ill fix it.  #1871 doesn't appear to have anything to do with this issue, so I hope it was just a mix up w/ the issue numbers...?

Attaching the build w/ the fix.. and here's OSGi console now (also removed unused ComponentHelper @Reference, since ModeUtil has effectively replaced that).

![image](https://user-images.githubusercontent.com/1451868/57494609-2140c880-7298-11e9-8c4d-d8aff5c57b80.png)

[acs-aem-commons-content-4.1.1-SNAPSHOT-min.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/3164434/acs-aem-commons-content-4.1.1-SNAPSHOT-min.zip)

**Comment by maurerstefan** [comment] 2019-05-13 06:45
Thanks @davidjgonzalez 

With the snapshot version the component is active and the servlet filter registered.

**Comment by kwin** [comment] 2019-06-11 05:40
Fixed with https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/e2ab5a6eb6436a4416a7a88a754d4011e8d619c0.

**Closed by kwin** 2019-06-11 05:40 UTC
Labels: bug
