### ISSUE TITLE
VersionedClientlibsTransformerFactory tries to load Clientlib with Hash

### ISSUE THREAD

**Issue by hluetolf-helvetia** [Adobe-Consulting-Services/acs-aem-commons#1857] opened 2019-04-25 10:05 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4 SP3
* [ ] ACS AEM Commons Version: 4.0.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

When rendering a page, the following log message is not written: 
15.03.2019 13:54:16.409 level=INFO [10.2.171.218 [1552654455690] GET /path/to/home.html HTTP/1.1] com.adobe.acs.commons.rewriter.impl.VersionedClientlibsTransformerFactory Refreshing client libraries cache, because /etc.clientlibs/os/core/clientlibs/clientlib-js.664e7fc7a8f796d3200d7ebb8063d8bb could not be found

Within the method resolveProxiedClientLibrary the clientlibs is tried to be found with the hash and thus cannot be found. If the clientlib would have been looked for without the hash (os/core/clientlibs/clientlib-js), it would imho work as expected.

### Actual Behavior

Every page rendering causes log messages:
15.03.2019 13:54:16.409 level=INFO [10.2.171.218 [1552654455690] GET /path/to/home.html HTTP/1.1] com.adobe.acs.commons.rewriter.impl.VersionedClientlibsTransformerFactory Refreshing client libraries cache, because /etc.clientlibs/os/core/clientlibs/clientlib-js.664e7fc7a8f796d3200d7ebb8063d8bb could not be found

### Steps to Reproduce

1. Have an instance of AEM 6.4 with acs-commons 4.0.0
2. Have a page that uses a client lib with allowProxy=true
3. Request that page
4. Message is being logged

### Links

None so far

**Comment by joerghoh** [comment] 2019-04-25 13:57
what is the actual repository path where this clientlib is located?

**Comment by joerghoh** [comment] 2019-04-25 14:40
I tried to reproduce it on vanilla AEM 6.5:

* request http://localhost:6502/editor.html/content/we-retail/us/en/experience.html and checked that I have lines like this in markup:
`<link rel="stylesheet" href="/etc.clientlibs/granite/ui/components/foundation/clientlibs/foundation.css" type="text/css">`
* install the latest snapshot of acs-aem-commons
* added "versioned-clientlib" to /libs/cq/config/rewriter/default (just as hack)
* reloaded the above page and checked the markup. Now I have this markup:
`<link rel="stylesheet" href="/etc.clientlibs/granite/ui/components/foundation/clientlibs/foundation.5f890da4d48d04ee6ebe778cb241d94f.css" type="text/css">` which seems quite ok to me.

Additionally I don't see that warning in the logs. I would strongly assume that on AEM 6.4.3 the situation is the same.

**Comment by hluetolf-helvetia** [comment] 2019-04-25 14:52
The real path of the clientlib is: /apps/os/core/clientlibs/clientlib-js
The path the VersionedClientlibsTransformerFactory tries to load is: /apps/os/core/clientlibs/clientlib-js.664e7fc7a8f796d3200d7ebb8063d8bb 
As this path does not exist the VersionedClientlibsTransformerFactory logs the INFO message.

Can you confirm that, while debugging VersionedClientlibsTransformerFactory on line 279, you get a valid absolutePath?

**Comment by joerghoh** [comment] 2019-04-25 16:12
The question I have: Why is the hash already appended at that time? It shouldn't.

It starts in `getVersionedPath()` (line 234) where the HtmlLIbrary object is populated. Later on the hash is appended. Thus the `libraryPath` parameter in that call must already contain the hash, which shouldn't be the case.

**Comment by davidjgonzalez** [comment] 2019-04-26 02:32
@hluetolf-helvetia I assume this is a function of the `allowProxy = true`? If you set `allowProxy = false` do this works correctly?

**Comment by hluetolf-helvetia** [comment] 2019-04-26 06:53
I have found the problem - it's the fact that we have an own mechanism that renders the path to the clientlib into the markup (with hash). There are several reasons we do so. 
I assume that when we change our mechanism to not add a hash itself the problem will be solved. Interestingly we did not face that problem with AEM 6.2 and an older version of ACS Commons.
Thanks for your support and Sorry for the circumstances.

**Comment by hluetolf-helvetia** [comment] 2019-04-26 07:33
Preventing our mechanism from adding the hash actually solved the problem. But there is one thing I would like to ask.

We use the Preload mechanism for faster page loading. For this, we first add a tag like following to the markup:
<link rel="preload" href="/etc.clientlibs/os/core/clientlibs/clientlib.min.css" as="css"/>

And later on, that library gets loaded as normal.
That preload tags are not rewritten with a hash. Is it possible to have hashes added as well for these tags?

**Comment by joerghoh** [comment] 2019-04-26 09:04
(Seems the markup didn't make it into your latest update ...)

**Comment by hluetolf-helvetia** [comment] 2019-04-26 09:09
Hi @joerghoh, ups, trying again:
`<link rel="preload" href="/etc.clientlibs/os/core/clientlibs/clientlib.min.css" as="css"/>`

**Comment by justinedelson** [comment] 2019-04-26 09:48
How is the tag with preload generated?

**Comment by joerghoh** [comment] 2019-04-26 09:53
Just taking the markup I posted above, have you already tried 

`<link rel="preload" href="/etc.clientlibs/os/core/clientlibs/clientlib.min.css" type="text/css" />`

?

**Comment by justinedelson** [comment] 2019-04-26 11:15
The reason I ask my question @hluetolf-helvetia is that AFAIK there's no support in AEM for adding the `preload` attribute to generated `<link>` tags (possibly/hopefully this information is outdated). So my guess is that in your component code you have something like this:

```
<link rel="preload" href="/etc.clientlibs/os/core/clientlibs/clientlib.min.css" as="css"/>
...some stuff here...
<sly data-sly-use.clientlib="/libs/granite/sightly/templates/clientlib.html"
     data-sly-call="${clientlib.css @ categories='os.core' "/>
```
Agree with @joerghoh  that adding the `type` attribute should address adding the hash, but it won't actually remove the double inclusion.

Incidentally, IMO it would be an interesting feature to add to ACS AEM Commons to get the `preload` attribute automatically added for client libraries included the "regular" way (e.g. by setting some property on the `cq:ClientLibraryFolder` node). That would avoid the double inclusion. This would probably make sense, though, as a separate rewriter processor.

**Comment by hluetolf-helvetia** [comment] 2019-04-26 12:06
@joerghoh Thank you very much for your feedback - adding the `type="text/css" ` to the CSS Preload tag actually worked and should be valid for preloading, great!

On the JS side it does not yet work as the parser expects JS libraries to be included with a script-Tag. Unfortunately the preloading mechanism expects preloaded JS libraries to be declared with link-Tags: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

@justinedelson We actually include the clientlibs in a different way because:
- Preloading (some JS libraries are preloaded in the head and then loaded at the bottom of the page) which is not supported by /libs/granite/sightly/templates/clientlib.html
- Ability to dynamically evaluate the clientlib categories within the Java model

In the head:
`<link rel="preload" href="${base.jsClientLibPath}" as="script">`

At the bottom:
`<script type="text/javascript" src="${base.jsClientLibPath}" defer></script>`

It would be very nice if there was a possibility to have these JS libraries preloaded as well.

**Comment by justinedelson** [comment] 2019-04-26 12:14
@hluetolf-helvetia I don't see any reason why those limitations can't be overcome by a separate transformer (which would run after the static reference rewriter) which automatically adds the preload `link` elements.

Referencing a client library by its path (vs. its category) is generally an anti-pattern since the path may change. Possibly this is not a concern if you are **only** handling your own client libraries this way, but the path of an OOTB client library is *not* considered to be part of its API (only the category is considered API).

**Comment by justinedelson** [comment] 2019-04-26 12:14
In any case, closing this issue. If you would like to contribute such a transformer, please open a separate issue/pull request.

**Closed by justinedelson** 2019-04-26 12:14 UTC

**Comment by hluetolf-helvetia** [comment] 2019-04-26 13:45
@justinedelson Thank you very much for your response. 
Just to make sure to have understood: you won't implement such a Transformer on your side for the moment, correct? 

One more thing: within our model we do work with categories, not with paths. The paths will then be resolved using the ClientLibrary API.

**Comment by justinedelson** [comment] 2019-04-26 16:25
@hluetolf-helvetia personally, I've more or less retired from day-to-day development :) this is obviously an interesting case, but to set your expectations properly, no I don't see myself doing this.

bq. One more thing: within our model we do work with categories, not with paths. The paths will then be resolved using the ClientLibrary API.

good to know.

**Comment by hluetolf-helvetia** [comment] 2019-04-30 11:50
Hi @justinedelson, thanks againg for your response.
We decided to rely on our own service and disabled the Versioned Clientlibs for the moment. 
If we should run into issues we would then rethink opening a new issue and contributing on this.
