### ISSUE TITLE
AEM 6.5 Service Pack 6.5.8 ACS:  5.0.4 : Version Clientlibs not loading

### ISSUE THREAD

**Issue by irenebijo** [Adobe-Consulting-Services/acs-aem-commons#2588] opened 2021-05-21 02:02 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______AEM 6.5 Service Pack 6.5.8
* [ ] ACS AEM Commons Version: _____ 5.0.4
* [ ] Reproducible on Latest? yes/no yes

### Expected Behavior-----------------------------------------------

Versioned clientlibs should load as  provided below:
/etc.clientlibs/org/kp/afd/foundation/clientlibs/clientlib-all.min.ACSHASH362a9395141885d8d8e6b2a96ea9eccc.css

### Actual Behavior

_Version Clientlibs is not  working  on Publisher:
Versioned Clientlibs are configured  based on the documentation 
https://adobe-consulting-services.github.io/acs-aem-commons/features/versioned-clientlibs/index.html
but versioned clientlibs are not  loading and instead loading as  /etc.clientlibs/org/kp/afd/foundation/clientlibs/clientlib-all.css

Publisher  ACS commons debug log----------------------------------

com.adobe.acs.commons.rewriter.impl.VersionedClientlibsTransformerFactory Could not find HtmlLibrary at path: /etc.clientlibs/org/kp/afd/foundation/clientlibs/clientlib-all
com.adobe.acs.commons.rewriter.impl.VersionedClientlibsTransformerFactory Versioned Path could not be created properly

but clientlibs are loading and accessible on the path /etc.clientlibs/org/kp/afd/foundation/clientlibs/clientlib-all.css

### Steps to Reproduce

Issue was unable to reproduce on local environment with all client code. Issue persist from lower to prod environments

### Links

_Links to related assets, e.g. content packages containing test components_
https://medschool.kp.org/homepage
https://medschool.kp.org/etc.clientlibs/org/kp/som/clientlibs/base.min.css

**Comment by kwin** [comment] 2021-05-21 07:43
This is a duplicate of #2577

**Closed by kwin** 2021-05-21 07:43 UTC
