### ISSUE TITLE
ACS Commons creates build issues in adobe cloud manager

### ISSUE THREAD

**Issue by Divya-Sekar** [Adobe-Consulting-Services/acs-aem-commons#2661] opened 2021-07-28 17:13 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______ AEM as Cloud Service
* [ ] ACS AEM Commons Version: _____ 5.0.6
* [ ] Reproducible on Latest? yes

### Expected Behavior

When i deploy ACS Commons in AEM as Cloud Service via cloud manager, it should not give build issues.

### Actual Behavior

When i deploy ACS Commons in AEM as Cloud Service via cloud manager, there are build issues getting created in acs-commons bundle and components (which includes Critical and Minor)

### Steps to Reproduce

Added ACS Commons dependency in for AEM as Cloud Service maven project as given here "https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html" and deployed in Cloud manager.

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by kwin** [comment] 2021-07-28 21:08
Duplicate of #2604

**Closed** 2021-07-28 21:08 UTC
