### ISSUE TITLE
AEM 6.2 send email from workflow with email template - getting invalid recipients exception

### ISSUE THREAD

**Issue by nimithakumar** [Adobe-Consulting-Services/acs-aem-commons#794] opened 2016-09-20 00:07 UTC
[order-brochure-email-confirm.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/481370/order-brochure-email-confirm.txt)
[email.docx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/481371/email.docx)

**Comment by justinedelson** [comment] 2016-09-20 00:19
Could you provide more information on exactly what you are doing and the result you are seeing?

**Comment by nimithakumar** [comment] 2016-09-20 00:43
I have a workflow which takes payload from the form and sends an email out using the order-brochure-email-confirm.txt, when it reaches this step the log file throws invalid email recipients exception and step remains active. This used to work in AEM 6.0 and we are trying to move this workflow to AEM 6.2 and the class we used in AEM 6.0 is no longer available in 6.2. How can I send an email in 6.2, in my second attachment I have attached screenshots of what I am doing in the workflow step. Thanks for your help in advance.

**Comment by justinedelson** [comment] 2016-09-20 00:47
I'm sorry, I'm still not following you. What is the "class we used in AEM 6.0 which is no longer available in 6.2"?

Can you post links to the screenshots (although I'm not really sure what they have to do with anything) rather than using MS Word?

What is the actual exception you are getting? Please provide a stack trace.

**Comment by nimithakumar** [comment] 2016-09-20 01:47
AEM 6.0 uses com.adobe.cq.social.commons.SendEmailProcess  which used to be used in DAM workflow step called send email , which is no longer available in 6.2. So I am now adding a step in the workflow and setting the process as send templated email which uses com.adobe.acs.commons.email.process.impl.sendTemplatedEmailProcess. I get below exception

20.09.2016 11:44:41.248 *INFO* [JobHandler: /etc/workflow/instances/server0/2016-09-16/order-brochure-workflow_9:/content/usergenerated/brokers/download-product-document/order-brochures/cq-gen1392003496609/1474335873659_1] au.com.zurich.workflow.OrderBrochureIdGen path ::  /content/zurich_au/brokers/downloads/order-brochures
20.09.2016 11:44:41.293 *ERROR* [JobHandler: /etc/workflow/instances/server0/2016-09-16/order-brochure-workflow_9:/content/usergenerated/brokers/download-product-document/order-brochures/cq-gen1392003496609/1474335873659_1] com.day.cq.workflow.compatibility.CQWorkflowProcessRunner Process execution resulted in an error: Invalid Recipients
java.lang.IllegalArgumentException: Invalid Recipients
	at com.adobe.acs.commons.email.impl.EmailServiceImpl.sendEmail(EmailServiceImpl.java:88)
	at com.adobe.acs.commons.email.process.impl.SendTemplatedEmailProcess.execute(SendTemplatedEmailProcess.java:220)
	at com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.execute(CQWorkflowProcessRunner.java:93)
	at com.adobe.granite.workflow.core.job.HandlerBase.executeProcess(HandlerBase.java:189)
	at com.adobe.granite.workflow.core.job.JobHandler.process(JobHandler.java:244)
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:500)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:291)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:58)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
20.09.2016 11:44:41.294 *ERROR* [JobHandler: /etc/workflow/instances/server0/2016-09-16/order-brochure-workflow_9:/content/usergenerated/brokers/download-product-document/order-brochures/cq-gen1392003496609/1474335873659_1] com.adobe.granite.workflow.core.job.JobHandler Process execution resulted in an error
com.adobe.granite.workflow.WorkflowException: Process execution resulted in an error
	at com.adobe.granite.workflow.core.job.HandlerBase.executeProcess(HandlerBase.java:199)
	at com.adobe.granite.workflow.core.job.JobHandler.process(JobHandler.java:244)
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:500)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:291)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:58)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
Caused by: com.adobe.granite.workflow.WorkflowException: Failed to execute process
	at com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.execute(CQWorkflowProcessRunner.java:108)
	at com.adobe.granite.workflow.core.job.HandlerBase.executeProcess(HandlerBase.java:189)
	... 8 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid Recipients
	at com.adobe.acs.commons.email.impl.EmailServiceImpl.sendEmail(EmailServiceImpl.java:88)
	at com.adobe.acs.commons.email.process.impl.SendTemplatedEmailProcess.execute(SendTemplatedEmailProcess.java:220)
	at com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.execute(CQWorkflowProcessRunner.java:93)
	... 9 common frames omitted
20.09.2016 11:44:41.681 *INFO* [10.64.212.174 [1474335881657] GET /libs/wcm/core/content/components.1474335873203.json HTTP/1.1] com.day.cq.wcm.core.impl.components.ComponentServlet provided components.

**Comment by justinedelson** [comment] 2016-09-20 20:43
as you can see in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/email/impl/EmailServiceImpl.java#L87, this exception is thrown when no recipients have been provided. Since you are not providing any recipients, that would seem like the expected behavior.

It seems like you are under the impression this is a replacement for `com.adobe.cq.social.commons.SendEmailProcess`. I don't believe that is the case.

**Comment by nimithakumar** [comment] 2016-09-20 22:59
Email Recipients are taken from the payload and added to the To in the template i have attached initially , I need to send the email to the person who has filled in the form as well as 2 other email addresses, 
How can I set these email addresses in this new process. I tried setting sendTo: argument with my email address in the step but am still getting this error. Thanks.

**Comment by justinedelson** [comment] 2016-09-21 00:12
Did you look at the documentation? http://adobe-consulting-services.github.io/acs-aem-commons/features/worflow-processes.html

There is no support for using the payload to define the To address. If this feature would be useful to you, feel free to create a pull request.

**Comment by nimithakumar** [comment] 2016-09-21 03:24
The form can be filled by any one, is there a way to take the email address in the field and set to sendTo: also other email addresses are email groups that are not AEM users, how can I set these email addresses as when I tried to directly set my email address to sendTo it did not work.
Sorry I am new to GIT what do you want me to pull? Thanks

**Comment by justinedelson** [comment] 2016-09-21 11:25
As I can see, you are describing two different things:

1. The to address needs to be set from the payload.
2. The sendTo workflow argument isn't working.

For #1, this is not documented nor supported. I don't know how you got the impression it was. If this is important to you, I would suggest implementing it and submitting a pull request with your changes. There are any number of guides to do this, including the details in our CONTRIBUTING guide.
For #2, you need to be more specific. What are you doing? what isn't working? How it be reproduced?

**Comment by davidjgonzalez** [comment] 2017-01-21 14:21
Closing as this doesnt sound like an issues with ACS Commons. Please feel free to re-open with exact details where the issues is with ACS Commons.

**Closed by davidjgonzalez** 2017-01-21 14:21 UTC
