### ISSUE TITLE
ACS AEM COMMONS not loading custom class through class loaded for Report builder

### ISSUE THREAD

**Issue by rakshithsirigeri** [Adobe-Consulting-Services/acs-aem-commons#2932] opened 2022-08-11 07:09 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.9
* [ ] ACS AEM Commons Version: 4.9.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

Whenever I try to create a custom query report executor for extending report builder, The custom class must be loaded

### Actual Behavior

ACS Commons throws Class not found exception
Caused by: com.adobe.acs.commons.reports.api.ReportException: Unable to find class for com.adobe.acs.commons.reports.models.CustomQueryReportExecutor
	at com.adobe.acs.commons.reports.internal.ReportExecutorProvider.getReportExecutor(ReportExecutorProvider.java:52) [com.adobe.acs.acs-aem-commons-bundle:4.9.0]
	at com.adobe.acs.commons.reports.internal.ReportCSVExportServlet.updateCSV(ReportCSVExportServlet.java:148) [com.adobe.acs.acs-aem-commons-bundle:4.9.0]
	at com.adobe.acs.commons.reports.internal.ReportCSVExportServlet.doGet(ReportCSVExportServlet.java:100) [com.adobe.acs.acs-aem-commons-bundle:4.9.0]
	... 139 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.adobe.acs.commons.reports.models.CustomQueryReportExecutor
	at org.apache.sling.commons.classloader.impl.ClassLoaderFacade.loadClass(ClassLoaderFacade.java:158) [org.apache.sling.commons.classloader:1.4.2]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.adobe.acs.commons.reports.internal.ReportExecutorProvider.getReportExecutor(ReportExecutorProvider.java:50) [com.adobe.acs.acs-aem-commons-bundle:4.9.0]
	... 141 common frames omitted

### Steps to Reproduce

Create a custom class implementing QueryExecutor interface and update the query config. When we try to download the report . It throws this error

**Comment by davidjgonzalez** [comment] 2022-08-17 17:24
@klcodanr any idea? IIRC this uses Sling's Dynamic Class loader?

**Comment by rakshithsirigeri** [comment] 2022-08-19 02:58
Hey @klcodanr , Yes it's happening in 6.5 with SP9.  Yes I tried exporting the package from bundle as well. It didn't help

**Comment by rakshithsirigeri** [comment] 2022-08-23 05:58
Hello @klcodanr  , any update on this? Thanks

**Comment by klcodanr** [comment] 2022-08-24 00:08
Hi @rakshithsirigeri Sorry I've not yet had a chance to do an investigation on this. I've cloned this bug into our internal issue tracker and added it to my work this sprint.

**Comment by klcodanr** [comment] 2022-08-24 14:25
I was unable to reproduce the issue @rakshithsirigeri, but I have a theory of what's going on. Did you create your CustomReportExecutor in the package `com.adobe.acs.commons.reports.models`?

That package is already published by ACS AEM Commons so I _suspect_ that OSGi is trying to look for your class within the ACS AEM Commons bundle rather than resolving it from your bundle. The solution is to change the package for your CustomReportExecutor to not be an Adobe-defined package, e.g. com.mycustomer.core.reports.CustomReportExecutor

Let me know if this resolves the issue.

**Comment by klcodanr** [comment] 2022-08-29 13:58
Any further questions / follow up @rakshithsirigeri ?

**Closed** 2022-09-01 15:45 UTC
Labels: bug
