### ISSUE TITLE
Dropdowns in MCP forms not working

### ISSUE THREAD

**Issue by MANID048** [Adobe-Consulting-Services/acs-aem-commons#3029] opened 2023-01-20 12:01 UTC
## Required Information

* AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM as a Cloud Service latest release
ACS AEM Commons Version: 5.4.0
Reproducible on Latest? yes

Expected Behavior
Dropdown fields within the MCP form should expand upon being clicked.

Actual Behavior
Dropdown fields within the MCP form do not expand upon being clicked.

Steps to Reproduce
Go to Tools > ACS AEM Commons > Manage Controlled Processes.
Click "Start Process" in the top-right corner.
Select a process that has a [dropdown](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/593af743a50ddfec3ded43825481484d4ed63c9d/bundle/src/main/java/com/adobe/acs/commons/mcp/form/SelectComponent.java) in the form (e.g. "Asset Folder Creator").
Try to expand the dropdown.

**Comment by MANID048** [comment] 2023-01-20 12:02
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2277. Same issue still there

**Comment by davidjgonzalez** [comment] 2023-01-20 16:23
It appears the problem is because the forms with the (coral) select are XHR'd in and injected into the "ready" DOM. Something changed where whatever initializes the select dropdown isnt triggering after the DOM injection. I've reached out to product to see if they have a solution to work around this change.

**Comment by davidjgonzalez** [comment] 2023-01-20 19:33
This should fix it: 
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3030

**Comment by davidjgonzalez** [comment] 2023-01-20 20:43
Fixed in v5.5.2 (just released)

**Closed by davidjgonzalez** 2023-01-20 20:43 UTC
Labels: bug
