### ISSUE TITLE
All records are not returned in the page when user generates report after checking 'Select All' checkbox

### ISSUE THREAD

**Issue by ShivangiHiray21** [Adobe-Consulting-Services/acs-aem-commons#1771] opened 2019-03-05 12:52 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.3, Service Pack 2
* [ ] ACS AEM Commons Version: 3.18.2
* [ ] Reproducible on Latest? yes/no Yes

### Expected Behavior

When the checkbox 'All results' is checked , it is expected to display whole result set in same page.

### Actual Behavior

If 'All Result' checkbox is selected , not all the rows are getting displayed on one page. Few of records are missing.
1.If the number of columns in result are less then it works as expected.
2.With more number of records, all the records are not getting displayed.

### Steps to Reproduce

Steps and initial background of this issue is mentioned in attached document.Please refer the same.

### Links
[SPOT-719.docx](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2930963/SPOT-719.docx)

**Comment by ShivangiHiray21** [comment] 2019-03-19 07:18
It is a Production Issue.. Could you please let me know when this functionality will be availqble...

**Comment by badvision** [comment] 2019-03-29 22:51
I suspect this is a duplicate of #1789 which I just fixed.

**Closed** 2019-06-04 23:18 UTC
Labels: bug, wontfix
