### ISSUE TITLE
Touch ui limit parsys fires ajax calls when hovering over components in authoring UI

### ISSUE THREAD

**Issue by Jarflux** [Adobe-Consulting-Services/acs-aem-commons#1049] opened 2017-07-26 12:16 UTC
**Problem**
When an author hovers on a component or parsys, ajax calls are fired from javascript to the author instance.
These ajax calls are fetching json information from within /etc/designs/.. with a selector '2'
F.e. http://localhost:4502/etc/designs/..../jcr:content/general/banner/contents.2.json
All these ajax calls return a 404 and so they serve no purpose but polluting our client/server logs and contributes to a high load on our author instance.
<img width="957" alt="screen shot 2017-07-26 at 14 05 08" src="https://user-images.githubusercontent.com/3426790/28620026-80f63f74-720b-11e7-9cb1-2067aed58a59.png">

**Our temporary fix** ( it will probably break the feature, but we are not using this )
Remove following lines prevents the ajax calls from beeing triggered.
/apps/acs-commons/touchui-widgets/source/touchui-limit-parsys.js:82 -> 96 
<img width="612" alt="screen shot 2017-07-26 at 14 01 01" src="https://user-images.githubusercontent.com/3426790/28619919-092e4450-720b-11e7-8cdd-669ceb140bad.png">

/apps/acs-commons/touchui-widgets/source/touchui-configure-parsys-placeholder.js:130
<img width="529" alt="screen shot 2017-07-26 at 14 00 45" src="https://user-images.githubusercontent.com/3426790/28619922-0cd43f06-720b-11e7-8496-9d2b157481a0.png">

Issue described on Adobe forums https://forums.adobe.com/thread/2325086

We are using AEM 6.1 with acs-commons 2.10.0.

**Comment by justinedelson** [comment] 2017-07-26 13:04
This is a duplicate of #989. That issue is labeled as help wanted. Feel free to supply a pull request.

**Closed** 2017-07-26 13:06 UTC
