### ISSUE TITLE
4.9.2 EnvironmentIndicator (Filter) breaks xml content in Servlet Response

### ISSUE THREAD

**Issue by LucaNerlich** [Adobe-Consulting-Services/acs-aem-commons#2477] opened 2020-11-17 12:50 UTC
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.5 / latest 6.4
* [x] ACS AEM Commons Version: 4.9.2
* [x] Reproducible on Latest? yes

### Expected Behavior

The following snippet should correctly write the xml content to the SlingResponse

```java
 @Override
    protected void doGet(final SlingHttpServletRequest req,
                         final SlingHttpServletResponse resp) throws ServletException, IOException {
        final Wartungsmodus wartungsmodus = new Wartungsmodus();
        wartungsmodus.setActive(false);
        ServletUtils.sendXmlObject(resp, wartungsmodus);
    }
```

### Actual Behavior

It actually writes it twice:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<maintenance>
    <active>false</active>
</maintenance>
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<maintenance>
    <active>false</active>
</maintenance>
```
This does **NOT** occur on 4.8.6

Example Screenshot
![image](https://user-images.githubusercontent.com/5942270/99391626-b899c980-28da-11eb-934e-3a6b33be6fcd.png)

### Steps to Reproduce

Create a simple Servlet:

```java
@Component(service = {Servlet.class})
@SlingServletResourceTypes(
        resourceTypes = "/apps/my/path",
        methods = HttpConstants.METHOD_GET)
@ServiceDescription("Simple Demo Servlet")
public class SimpleServlet extends SlingSafeMethodsServlet {
    
    @Override
    protected void doGet(final SlingHttpServletRequest req,
                         final SlingHttpServletResponse resp) throws ServletException, IOException {
        final Wartungsmodus wartungsmodus = new Wartungsmodus();
        wartungsmodus.setActive(false);
        ServletUtils.sendXmlObject(resp, wartungsmodus);
    }
}
```

Create the xml Model:

```java
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "maintenance")
@XmlAccessorType(XmlAccessType.NONE)
public class Wartungsmodus {
    
    @XmlElement(name = "active", required = true)
    private boolean active;
    
    public boolean isActive() {
        return active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
}
```

Use JaxB to create the xml content:

JaxbMapper.java
```java
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import java.io.ByteArrayOutputStream;
import java.io.UnsupportedEncodingException;

public class JaxbMapper {
    private static final String ENCODING = "UTF-8";
    
    public static String toString(final Object object) throws JAXBException, UnsupportedEncodingException {
        
        final JAXBContext context = JAXBContext.newInstance(object.getClass());
        final Marshaller marshaller = context.createMarshaller();
        
        marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
        marshaller.setProperty(Marshaller.JAXB_ENCODING, ENCODING);
        
        final ByteArrayOutputStream baos = new ByteArrayOutputStream();
        marshaller.marshal(object, baos);
        
        return baos.toString(ENCODING);
    }
}
```

Call and write to the respone:

```java
import org.apache.sling.api.SlingHttpServletResponse;

public class ServletUtils {
    
    private static final String XML_CONTENT_TYPE = "application/xml; charset=UTF-8";
    
    public static void sendXmlObject(final SlingHttpServletResponse response, final Object object) {
        try {
            final String stringObject = JaxbMapper.toString(object);
            response.setContentType(XML_CONTENT_TYPE);
            response.getWriter().write(stringObject);
        } catch (final Exception exception) {
            // [...]
        }
    }
}
```

Create and use the EnvironmentIndicator:

jcr_root/apps/dummyproject/conf/config.author/com.adobe.acs.commons.wcm.impl.AemEnvironmentIndicatorFilter.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:sling="http://sling.apache.org/jcr/sling/1.0"
    jcr:primaryType="sling:OsgiConfig"
    browser-title-prefix=""
    css-color="orange"
    css-override="#acs-commons-env-indicator { display: none; pointer-events: none; color: #bbb; opacity: 0.7; mix-blend-mode: difference; position: fixed; top: 0; left: 70%; width: 250px; margin-left: -63px; height: 24px; font: bold 14px/20px sans-serif; text-align: center; border-radius: 4px; border-top-width: 0; z-index: 100000000000000; }"
    inner-html="${APP} ${STAGE} ${RG}${NR} (${OSPRELEASE}) &lt;!-- flavor=${FLAVOR} stackname=${STACKNAME}  instnr=${INSTNR} pv=${PV} rs=${RS} rg=${RG} rz=${RZ}-->"/>

```

**Comment by kwin** [comment] 2020-11-19 16:19
Can this be reproduced with any OOTB XML servlets by chance?

**Comment by LucaNerlich** [comment] 2020-11-19 17:19
Havent tried it, sorry. Ill also be on vacation for the next 10days - so I wont be able to test it for a couple of days.

**Comment by kwin** [comment] 2020-11-21 19:00
I think this is a duplicate of #2475. Can you ty with the PR attached there?

**Closed** 2020-12-11 15:40 UTC
