### ISSUE TITLE
replace JSP files by HTL and Sling models (if required)

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/acs-aem-commons#1860] opened 2019-04-26 11:52 UTC
At the moment we have a huge number of JSP files in the content-package, but we lack tests cases for them. I would even argue, that these are not systematically tested when we adopt a new AEM release.

I propose to work towards dropping all JSPs and replace them by HTL scripts plus sling models. Of course there might be a few places, where this is not possible, but for the majority of cases this should not a problem.

**Comment by davidjgonzalez** [comment] 2019-04-26 14:35
This should be tackled w/ discrete issues for EACH feature being updated, and not generally using this GH issue. Whoever is performing the conversion should **_fully_** understand the feature they are updating.

I would prioritize features that still depend on ClassicUI, such as Dispatch Flusher, or the Packagers - since the shift to TouchUI necessitates may code updates anyhow.

Keep in mind that Unit tests do not guarantee working functionality (as I've hope we've learned through all the bugs we have against features with ~robust unit test suites) so full regression testing for these rewrites is required -- we've been burned by the worldview that Unit tests are sufficient in verifying functionality over the past few months.

As part of this, we should look at updating the "utility page" AngularJS framework to be something more modern, and roll that change out in tandem w/ updates that include this.

Lastly, IMO, there way more ROI on resolving open bugs (actual issues w/ functionality) rather than rewriting features that work just fine, just to move them off JSP. That said if you enjoy re-writing existing features, its your time, not mine :)

**Comment by joerghoh** [comment] 2019-04-26 14:41
:-)

Agree to your statement, that unless you enjoy doing that work, it does not have immediate value. But instead of fixing some issues in JSPs, which can be avoided by using HTL, we should consider to migrate it to HTL. 
I am trying to do that for #1839 right now.

**Closed** 2019-07-02 16:10 UTC
Labels: standardization, technical enhancement, wontfix
