### ISSUE TITLE
[DUPLICATE] Bundle not starting on AEM as a Cloud Service SDK

### ISSUE THREAD

**Issue by tomhpeeters** [Adobe-Consulting-Services/acs-aem-commons#2352] opened 2020-06-29 11:12 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: aem-sdk-quickstart-2020.6.3766.20200619T110731Z-200604
* [ ] ACS AEM Commons Version: 4.7.0 (min)
* [ ] Reproducible on Latest? yes

### Expected Behavior

ACS Commons bundle should start

### Actual Behavior

ACS Commons bundle does not start but stays in status "installed". Following error is visible in the logfile:

29.06.2020 12:17:27.777 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleStartTask Could not start bundle com.adobe.acs.acs-aem-commons-bundle [525]. Reason: {}. Will retry.
org.osgi.framework.BundleException: Unable to resolve com.adobe.acs.acs-aem-commons-bundle [525](R 525.0): missing requirement [com.adobe.acs.acs-aem-commons-bundle [525](R 525.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.dam.api.collection)(version>=1.0.0)(!(version>=2.0.0))) Unresolved requirements: [[com.adobe.acs.acs-aem-commons-bundle [525](R 525.0)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.dam.api.collection)(version>=1.0.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:97) [org.apache.sling.installer.core:3.11.4]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:918) [org.apache.sling.installer.core:3.11.4]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:755) [org.apache.sling.installer.core:3.11.4]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:304) [org.apache.sling.installer.core:3.11.4]
	at java.base/java.lang.Thread.run(Thread.java:834)

### Steps to Reproduce

- Install latest AEM as a Cloud Service SDK
- Upload ACS Commons min zip to package manager and install

**Comment by joerghoh** [comment] 2020-06-29 12:50
Duplicate of #2298

**Comment by joerghoh** [comment] 2020-07-25 17:38
Clsing as duplicate if #2298

**Closed by joerghoh** 2020-07-25 17:38 UTC
