### ISSUE TITLE
/var/acs-commons/on-deploy-scripts-status never gets created

### ISSUE THREAD

**Issue by Ronald-Diemicke** [Adobe-Consulting-Services/acs-aem-commons#2046] opened 2019-09-18 17:53 UTC
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.1
* [x] ACS AEM Commons Version: 4.3.2
* [x] Reproducible on Latest? yes

### Expected Behavior

I would expect that installing the ACS commons package would create the /var/acs-commons/on-deploy-scripts-status folder and that acs-commons-on-deploy-scripts-service
user would have access to it.

### Actual Behavior

The /var/acs-commons/on-deploy-scripts-status folder group doesn't get created.
acs-commons-on-deploy-scripts-service user does not get rights setup for it.

### Steps to Reproduce

Install AEM 6.5.
Install Service Pack 1
Install ACS Commons 4.3.2

**Comment by ahmed-musallam** [comment] 2019-09-18 19:21
I can confirm this. 

the filter does not include it see: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/595507aa2320be206c85a3069c91e70060c9b162/content/src/main/content/META-INF/vault/filter.xml#L104

**Comment by kwin** [comment] 2019-09-18 19:49
I think this is a duplicate of #2044.

**Comment by ahmed-musallam** [comment] 2019-09-18 20:00
yes, the report in #2044 does log the errors:

```
ERROR] ValidationViolation: "Node /var/acs-commons/on-deploy-scripts-status/rep:policy is not contained in any of the filter rules", filePath=jcr_root/var/acs-commons/on-deploy-scripts-status/_rep_policy.xml, nodePath=/var/acs-commons/on-deploy-scripts-status/rep:policy, line=3
[ERROR] ValidationViolation: "Node /var/acs-commons/on-deploy-scripts-status/rep:policy/allow is not contained in any of the filter rules", filePath=jcr_root/var/acs-commons/on-deploy-scripts-status/_rep_policy.xml, nodePath=/var/acs-commons/on-deploy-scripts-status/rep:policy/allow, line=7
[ERROR] ValidationViolation: "Node /var/acs-commons/on-deploy-scripts-status/README.txt is not contained in any of the filter rules", filePath=jcr_root/var/acs-commons/on-deploy-scripts-status/README.txt, nodePath=/var/acs-commons/on-deploy-scripts-status/README.txt
[ERROR] ValidationViolation: "Node /var/acs-commons/on-deploy-scripts-status is not contained in any of the filter rules", filePath=jcr_root/var/acs-commons/on-deploy-scripts-status/.content.xml, nodePath=/var/acs-commons/on-deploy-scripts-status, line=4
```

If they plan is to fix them all together, then yes that is a duplicate.

But I'd keep this issue because it directly impacts the on deploy script functionality. And fixing this takes priority and is faster than fixing everything in #2044

**Comment by Ronald-Diemicke** [comment] 2019-09-18 23:13
@kwin - you're right - this is a duplicate of #2044 - I didn't realize that this was part of that issue until you pointed it out, but @ahmed-musallam has a point that on-deploy is dead in the water until this is fixed.

I took a stab initially - but I saw you had a more comprehensive fix - what you have encompasses what I had, and then some, so I opened #2047 and credited you. This should fix this issue.

**Comment by ahmed-musallam** [comment] 2019-09-20 19:31
For others facing this issue here is a temporary fix:

add this folder to your project (don't forget the `_rep_policy.xml` file )
https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/e3be724e64d084c66e169efefcccc28d0f175d2a/ui.content/src/main/content/jcr_root/home/users/system/acs-commons/on-deploy-scripts-service

then in your `filter.xml` add:

```
    <filter root="/var/acs-commons" mode="merge"/>
```

this will fix it.

Make sure this is included in the same package the installs your bundle! (typically `ui.apps`)

**Closed** 2019-11-27 01:40 UTC
Labels: wontfix
