### ISSUE TITLE
ACS-Commons Redirect Manager: Context-Aware Configuration Not Showing in Redirects Console

### ISSUE THREAD

**Issue by sravanikancharla455** [Adobe-Consulting-Services/acs-aem-commons#3486] opened 2024-12-03 11:21 UTC
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: Cloud Latest (2024.11.0)
* [x] ACS AEM Commons Version: 6.9.4
* [x] Reproducible on Latest? yes

### Expected Behavior

The context configuration should be visible and accessible in the redirects console, allowing users to manage and modify redirects based on specific contexts.

### Actual Behavior

The context configuration is not appearing in the ACS-Commons Redirect Manager's console. Unable to view or modify the context configurations for redirects in the ACS-Commons Redirect Manager, which is causing issues with redirect management

### Steps to Reproduce

Navigate to the ACS-Commons.
Access the Manage Redirects console.
Create Context Aware Redirect Configuration. (e.g, tried to create for /conf/redirectconf)
The context configuration, which should be displayed alongside the redirects, is missing.
No context configurations appear, even when configured properly but showing in CRX-DE.

### Links

_Links to related assets, e.g. content packages containing test components_

<img width="957" alt="acs-commons-redirect-issue" src="https://github.com/user-attachments/assets/6380bb38-f3c8-41d1-a32f-c2eea241cec4">
<img width="941" alt="acs-commons-redirect-issue-1" src="https://github.com/user-attachments/assets/6b9f46df-cbf8-4b45-83c9-51a10088ced7">

@kwin @YegorKozlov

**Comment by YegorKozlov** [comment] 2024-12-05 08:08
duplicate of https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3479

the PR was merged, the issue should be fixed in next release

**Closed by YegorKozlov** 2024-12-05 08:08 UTC
Labels: duplicate
