### ISSUE TITLE
ACS Commons 4.3.x Fails to install on upgraded AEM from 6.4.2 to 6.5 if 'everyone' group is in a deep hierarchy

### ISSUE THREAD

**Issue by ichirital** [Adobe-Consulting-Services/acs-aem-commons#2069] opened 2019-10-07 13:12 UTC
## Required Information

* AEM Version, including Service Packs, Cumulative Fix Packs, etc: **AEM 6.4.2 upgraded to AEM 6.5**
* ACS AEM Commons Version: **4.3.0 or later**
* Reproducible on Latest? **yes**
* On our instance, the **everyone** group is located in /home/groups/e/everyone/ rep:AuthorizableFolder which is not causing any issues in AEM 6.4.x

### Expected Behavior

We were using ACS Commons 3.18.2 with AEM 6.4 and after upgrade we have tried installing ACS Commons 4.3.2. We expect the package to install and bundles to start.

### Actual Behavior

Installation fails in CRX Package Manager with an error "Could not install Package constraint violation exception" - see attachment.
 
After moving the group, it does install, however it appears to be traversing the entire repository to do so and hence taking much longer to install on bigger repositories.

### Steps to Reproduce

Create AEM 6.4 vanilla instance
In CRX DE, create extra rep:AuthorizableFolder and swap folder names and move them until there is a hierarchy similar to the one below
![image](https://user-images.githubusercontent.com/15053333/66314784-71d25580-e90c-11e9-8d1b-bf1221e2a56f.png)
Upgrade the instance to 6.5
Attempt to install ACS Commons (e.g. 4.3.0 or later)
The error below will come up.
![image](https://user-images.githubusercontent.com/15053333/66314818-7f87db00-e90c-11e9-8154-69ed44a7c8e2.png)

**Comment by justinedelson** [comment] 2019-10-10 17:13
I still do not understand what constraint is being violated here. ACS AEM Commons does not touch this node.

**Comment by ichirital** [comment] 2019-10-10 20:16
Agreed, however this is the behaviour and reproducible on vanilla instance. It does appear indeed like it's touching nodes that are not in the filter.

**Comment by joerghoh** [comment] 2019-11-01 18:16
Hm, I wonder a bit about the structure.

There is 
* /home/groups/e/everyone and
* /home/groups/e/everyone/<hash>

And according to the exception "/home/groups/e/everyone" is a rep:AuthorizableFolder and thus does not allow an nt:unstructured child node. Btw when testing it (manually adding the profile below the everyone folder) you get an OakConstraint0001, but not an OakConstraint0025 exception.

In AEM 6.4 ootb the path ``/home/groups/e/everyone`` is has the primary type "rep:group", so your state in AEM 6.4 already looks a bit unusal and surprising. Which is probably why this problem has not yet been reported. Because in an vanilla 6.4 (even migrated to 6.5) this should work.

But: I agree to Justin, there is no way how the package installation of ACS AEM Commons could deal with this path, because it is neither in the content itself (ui.apps) nor part of any filter.

**Comment by justinedelson** [comment] 2019-11-01 19:18
I'm not understanding why you want to move `/home/groups/e/everyone` to be `/home/groups/e/everyone/everyone`. The node structure under `/home/groups` should really be managed by Oak.

That said, I _tried_ following the steps to reproduce and neither CRX DE Lite nor CRX Explorer would actually allow me to move a `rep:Group` node.

**Comment by ichirital** [comment] 2019-11-12 14:48
Hi Justin, Joerg,

Thank you for your time investigating this. I don't _want_ the "everyone" group to be in the hierarchy /home/groups/e/everyone/everyone, this was a configuration set up by mistake on the 6.4 instance, so it was not intended and there is no specific reason for it to be in this way.

To simulate moving the group on a vanilla instance I followed the below steps in CRX DE:
* rename /home/groups/e rep:AuthorizableFolder to /home/groups/everyone
* create /home/groups/e rep:AuthorizableFolder  
* drag & drop "/home/groups/everyone" into the newly created "/home/groups/e"

As a result, the "everyone" group will be in the hierarchy /home/groups/e/everyone (and so will be the "experience-fragments-editors" group, but this group is of no concern for this scenario).

In CRX Explorer rename the group "everyone" to something like "4zhvJ2jN3Kys9SLOQnfY" (which the netcentric AC tool does / did).

I tried again to reproduce this locally on a 6.4 vanilla instance, upgraded to 6.5 and installed acs-aem-commons-content-4.3.2-min.zip, issue is occurring. I have made a recording, will try to post it here.

This is not a very common scenario for most users of the library and we have worked around it also, so I understand if it's not a high priority issue at the moment.

Regards,
Irina

**Comment by badvision** [comment] 2019-12-02 15:47
Please post your work-around so others can benefit (if you have a moment) -- otherwise I'll close this out unless we can more easily reproduce this or if @adamcin has some magic Oak Pal check to help spot any packaging issues that could cause this kind of thing.

**Closed by badvision** 2019-12-02 15:47 UTC
