### ISSUE TITLE
DispatcherFlushRules break replication in 6.3.3.1

### ISSUE THREAD

**Issue by rubenpax** [Adobe-Consulting-Services/acs-aem-commons#1668] opened 2019-01-08 05:41 UTC
Hi All,

I am facing an issue while replicating pages, which has dispatcher flush rules configured as per ACS common configuration. Suddenly we started to face this issue after install SP3 and CFP1 on top of AEM 6.3.2.0.

We have an agent to flush certain resources (.json files) when a page under certain pattern is being replicated from author to publish. While doing so, we are facing the below error in logs:

**flush agent.log:**

```
ERROR - flush_resource_only : Unable to build content for agent 'flush_resource_only'.Agent User 'null' does not sufficient permission on '/bin/myproject/home'.
ERROR - flush_resource_only : Error while building replication content com.day.cq.replication.AccessDeniedException: Replicaiton Agent [flush_resource_only]- Agent user [null] doesn't have sufficient permission on [/bin/myproject/home]
```

Also while replicating, I am seeing the warning message in the siteadmin console at the right top as shown below:

![](https://forums.adobe.com/servlet/JiveServlet/showImage/2-10853683-1662225/pastedImage_2.png)

This issue is as same as the following GIT post: #1636 but AEM versions are different.

 PS: We have validated permission for root path in AEM as explained in acs-commons-dispatcher-flush-service system user dispatcher flush ACLs for jcr:removeNode · Issue #1287 · Adobe-Consulti… . But still the same issue.

 Thanks in advance for any pointers.

**Comment by davidjgonzalez** [comment] 2019-01-08 14:34
@rubenpax the interesting thing here is 

1) It appears youre trying to invalidate a synthetic path (i assume/hope that `/bin/myproject/home` is not a real resource.
2) Your user to flush is "null" ... i cant figure out how this is possible based on #1287 

can you reproduce this on a vanilla 6.3.3.1? Can you also provide your flush rule osgi configuration?

**Comment by davidjgonzalez** [comment] 2019-01-08 14:46
also - the issue w/ the original issue (per comments) was an ACL was not deployed correctly due to ACS commons acl merge policy (merge preserve)... https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1287#issuecomment-378463681

can you validate this (but again, it seems strange you're replicating whats traditionally a servlet path)

**Comment by rubenpax** [comment] 2019-01-09 10:05
Hi David,

Thanks for your reply. Please find the response for your queries as follows:

1. It appears youre trying to invalidate a synthetic path (i assume/hope that /bin/myproject/home is not a real resource.
**[Response]: We have a servlet and which returns a JSON response. Our design is to cache the JSON files and we have flush rules configure to DELETE those json files whenever corresponding pages are replicated from Author to Publish instance.**

**The same set-up was working since years right from AEM6.1 and as well as in AEM6.3 SP2. I simulated the same in my local machine and found that, this issue exist only after installing CFP-1 on top of AEM 6.3 + SP3. Before installing CFP-1, no issues found. The whole configurations were working till AEM 6.3.3.0**

2. Your user to flush is "null" ... i cant figure out how this is possible based on #1287
**[Response]: We never configured "Agent User ID" field in the flush resource only agent (Please refer the below snap). Which means it usually takes the system user. But after installing CFP-1 (AEM 6.3.3.1) we are seeing this "null" error in logs.**

![image](https://user-images.githubusercontent.com/17138046/50892210-fa76a080-1423-11e9-8e5c-0ab6705825b9.png)

Any further suggestions?

Thank you!

**Comment by dinesh-akm** [comment] 2019-01-09 10:57
Hi David,

I and Ruben work for the same team. Please find the further analysis on the issue. It is very clear that Adobe has made some changes in the com.adobe.granite.replication.core-6.2.26-CQ630-B0011.jar bundle in com.day.cq.replication.impl.ReplicatorImpl class. Where as the previous versions of the same class has different code.

I could see there are additional conditions added for hidden paths and its sessions in the latest code. Please find the attached snap shots, which has the comparison of com.day.cq.replication.impl.ReplicatorImpl class in com.adobe.granite.replication.core-6.2.26-CQ630-B0011.jar and com.adobe.granite.replication.core-6.2.26-CQ630-B0002.jar.

![image](https://user-images.githubusercontent.com/39952167/50895094-1893cf00-142b-11e9-9f79-dc3a1d8bc244.png)

![image](https://user-images.githubusercontent.com/39952167/50895137-382af780-142b-11e9-980d-97bb40ac0e81.png)

I believe the same has to be fixed in ACS Common Code.

Thanks!

**Comment by justinedelson** [comment] 2019-01-09 14:18
@dinesh-akm your last comment included Adobe IP. I have deleted it.

**Comment by justinedelson** [comment] 2019-01-09 14:30
On its face, this is not an issue with ACS AEM Commons. This should be reproducible by direct invocation of the Replication API (since that is all the Dispatcher Flush Rules is doing). If you enable debug logging on `com.adobe.acs.commons.replication.dispatcher.impl.DispatcherFlusherImpl` you can see the specific parameters passed to the Replication API. Using this information, it should be trivial to implement a test case which bypasses ACS AEM Commons.

**Closed by justinedelson** 2019-01-09 14:30 UTC

**Comment by dinesh-akm** [comment] 2019-01-09 15:39
> @dinesh-akm your last comment included Adobe IP. I have deleted it.

Hi Justin,

Thanks for the concluding pointers and also for removing the comment with Adobe's IP. Apologies for the same.

**Comment by grtwloop** [comment] 2019-04-25 19:39
@rubenpax we have the exactly same problem. Would you share how you resolved it later?
