### ISSUE TITLE
We are facing some critical bug during code scanning in deployment

### ISSUE THREAD

**Issue by Rk-F5** [Adobe-Consulting-Services/acs-aem-commons#2609] opened 2021-06-16 05:41 UTC
Hi Team,

Please find attached the excel sheet containing the logs, which has 5 critical bugs 
all related to OOB acs-commons.

Kindly help in providing some resolution as this impact in the CI/CD deployment. This issue is available in staging environment as well
[build_project_issues.xls](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/6660706/build_project_issues.xls)

**Comment by by-4x1** [comment] 2021-06-19 00:13
@Rk-F5 This looks to be a duplicate of https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2604 ?  The "@ProviderType should not be implemented by custom code." CQBP-84 Critical Issue ?

**Closed** 2021-06-20 20:53 UTC

**Comment by kwin** [comment] 2021-06-20 20:55
Closed as duplicate of #2604
