### ISSUE TITLE
ACS Commons service users missing in our environment AEM 6.5 service pack 13

### ISSUE THREAD

**Issue by AsadShafi-AnF** [Adobe-Consulting-Services/acs-aem-commons#3011] opened 2022-12-20 17:23 UTC
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5 with SP 6.5.13
* [X] ACS AEM Commons Version: 5.10, 5.20, 5.40
* [X] Reproducible on AEM 6.5 SP 13? yes

### Expected Behavior

AEM useradmin should show 23 service users for aem acs commons

### Actual Behavior

we are only seeing 13 or 14 service users in useradmin

### Steps to Reproduce

navigate to http://localhost:4502/useradmin and filter acs in search bar

### Links

https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html

Implementation details : 

<img width="1786" alt="Screenshot 2022-12-20 at 10 22 30 PM" src="https://user-images.githubusercontent.com/120579979/208727891-f7ffa0f5-58a5-4df0-9f3b-aaf3b8af4437.png">
<img width="1786" alt="Screenshot 2022-12-20 at 10 22 26 PM" src="https://user-images.githubusercontent.com/120579979/208727928-8c185cbc-4a55-4457-b1b1-28592a110922.png">
<img width="1786" alt="Screenshot 2022-12-20 at 10 22 18 PM" src="https://user-images.githubusercontent.com/120579979/208727938-25afd086-4441-4a75-aac7-c30167c39335.png">

**Comment by davidjgonzalez** [comment] 2022-12-21 16:55
If you just install acs-aem-commons content package directly, do they get installed? 

Also, per the docs you linked - the `min` classifier was removed in version 5.3.0 of ACS Commons.

**Comment by AsadShafi-AnF** [comment] 2022-12-21 18:37
> If you just install acs-aem-commons content package directly, do they get installed?
> 
> Also, per the docs you linked - the `min` classifier was removed in version 5.3.0 of ACS Commons.

If we install acs-aem-commons content package directly through crx package manager we are getting only 13 service users and those are not sufficient

The min classifier is compatible with 5.1.0 and currently we have 5.1.0
We tried with 5.30, 5.40 higher versions but no luck

Can you provide a solution to this ?

**Comment by davidjgonzalez** [comment] 2022-12-21 18:46
I think something is wrong with your AEM install.. i just installed 5.4.0 content package on 6.5.13 and i see all of them:

![2022-12-21 at 1 45 PM](https://user-images.githubusercontent.com/1451868/208980508-54e4b2f6-ce18-4ac9-a502-38cbb20a52c0.png)

Can you take a screenshot if which one you have vs dont have? I wonder if something is wrong w/ your AEM is having problems with either RepoInit or package manager's installation of principals.

Have you tried this on a clean, vanilla Sp13 like i did above?

**Comment by AsadShafi-AnF** [comment] 2022-12-21 19:12
> I think something is wrong with your AEM install.. i just installed 5.4.0 content package on 6.5.13 and i see all of them:
> 
> ![2022-12-21 at 1 45 PM](https://user-images.githubusercontent.com/1451868/208980508-54e4b2f6-ce18-4ac9-a502-38cbb20a52c0.png)
> 
> Can you take a screenshot if which one you have vs dont have? I wonder if something is wrong w/ your AEM is having problems with either RepoInit or package manager's installation of principals.
> 
> Have you tried this on a clean, vanilla Sp13 like i did above?

We are only seeing 13 users as shown in the screen shot and we have AEM 6.5.13

<img width="1786" alt="Screenshot 2022-12-22 at 12 09 59 AM" src="https://user-images.githubusercontent.com/120579979/208984768-f19605c0-9692-4f18-be6e-9e64431465c2.png">

**Comment by AsadShafi-AnF** [comment] 2022-12-21 19:13
I completely agree can you let us know what can be possibly messing up with service users creation ?

**Comment by YegorKozlov** [comment] 2022-12-21 19:25
Try uninstalling the previous version, make sure /apps/acs-commons was deleted, and then install ACS Commons over again.

I had cases when Package Manager acted funny and wouldn't fully install . Deletion + re-install usually helped.

**Comment by AsadShafi-AnF** [comment] 2022-12-21 20:37
Is uninstall and complete delete of apps/acs- commons  and packages safe?
Since some features are depending upon

Also can we do same using the pom but again can deleting completely be safe ?
________________________________

**Comment by davidjgonzalez** [comment] 2022-12-21 22:26
It appears the users defined in RepoInit (in the content project itself) are not being installed -- the 13 defined in ui.content project are [1].  Can you verify in package manager the  `content` project (as well as the `ui.content`) ACS Commons projects are installed? It seems like you have a problem w your RepoInit picking up these files. Can you verify that RepoInit is working otherwise on your AEM install?


[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/ui.content/src/main/content/jcr_root/home/users/system/acs-commons

**Comment by AsadShafi-AnF** [comment] 2022-12-22 12:19
> It appears the users defined in RepoInit (in the content project itself) are not being installed -- the 13 defined in ui.content project are [1]. Can you verify in package manager the `content` project (as well as the `ui.content`) ACS Commons projects are installed? It seems like you have a problem w your RepoInit picking up these files. Can you verify that RepoInit is working otherwise on your AEM install?
> 
> [1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/ui.content/src/main/content/jcr_root/home/users/system/acs-commons

Hi davidjgonzalez

The link you shared = " https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/ui.content/src/main/content/jcr_root/home/users/system/acs-commons "  it has 13 users only which we are having already 
we are looking for 23 service users (if we mistaken and there are only these 13 let us know)

however installing content pakcage manually provides 23 users some times but we are installing the content package through pom.xml approach as shared in the above main screen shots.

**Comment by davidjgonzalez** [comment] 2022-12-22 14:19
It sounds like you have a problem with your installations Sling RepoInit - or JCR installer, as it doesn't seem to be picking up the users  related by repo unit. Here's what I suggest:

1. In your own project, make a repo init script that creates a service user in a similar fashion as acs commons does w repo init 
2. Deploy your project and validate if it consistently installs/doesn't install
3. Log a adobe customer care issue  with the issue being repo init doesn't work

It sounds like you have a larger issue with AEM that is impacting acs commons install

**Comment by bdhoine** [comment] 2023-02-01 19:59
we noticed when reinstalling the content package the users in `/home/users/system/acs-commons` are removed by the filter on https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/acs-aem-commons-5.5.2/ui.content/src/main/content/META-INF/vault/filter.xml#L80 and as you can see here https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/acs-aem-commons-5.5.2/content/src/main/content/jcr_root/apps/acs-commons/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-root-acls.config#L3 some service users are created on that path by repoinit scripts and thus will be gone on package install (unless you do a restart)

**Comment by gvschilling** [comment] 2023-03-01 18:47
I was able to reproduce this with the following steps:

1. Create a new AEM 6.5 instance
2. Install SP 15
3. Install `acs-aem-commons-content:5.7.0`
4. Search for "acs" in `/useradmin`
5. The following users are returned:
    * acs-commons-automatic-package-replicator-service
    * acs-commons-bulk-workflow-service
    * acs-commons-component-error-handler-service
    * acs-commons-dispatcher-flush-service
    * acs-commons-email-service
    * acs-commons-ensure-oak-index-service
    * acs-commons-ensure-service-user-service
    * acs-commons-error-page-handler-service
    * acs-commons-file-fetch-service
    * acs-commons-form-helper-service
    * acs-commons-httpcache-jcr-storage-service
    * acs-commons-manage-controlled-processes-service
    * acs-commons-manage-redirects-service
    * acs-commons-marketo-conf-service
    * acs-commons-on-deploy-scripts-service
    * acs-commons-package-garbage-collection-service
    * acs-commons-package-replication-status-event-service
    * acs-commons-remote-assets-service
    * acs-commons-review-task-asset-mover-service
    * acs-commons-shared-component-props-service
    * acs-commons-system-notifications-service
    * acs-commons-twitter-updater-service
    * acs-commons-workflow-remover-service
    * acs-commons-workflowpackagemanager-service
7. Navigate back to `/useradmin` and search for "acs" again
8. Only the following are install:
    * acs-commons-bulk-workflow-service
    * acs-commons-component-error-handler-service
    * acs-commons-email-service
    * acs-commons-error-page-handler-service
    * acs-commons-file-fetch-service
    * acs-commons-form-helper-service
    * acs-commons-httpcache-jcr-storage-service
    * acs-commons-manage-controlled-processes-service
    * acs-commons-manage-redirects-service
    * acs-commons-remote-assets-service
    * acs-commons-review-task-asset-mover-service
    * acs-commons-shared-component-props-service
    * acs-commons-system-notifications-service
    * acs-commons-twitter-updater-service

**Comment by gvschilling** [comment] 2023-03-06 21:49
I tested this with 6.0.0 this morning and it looks to have been resolved. There was no ticket/issue assigned to the commit, but rather looks like tech debt as apart of the major release

**Closed** 2023-03-06 22:25 UTC
Labels: question

**Comment by davidjgonzalez** [comment] 2023-03-06 23:05
@gvschilling Hi - yes, as part of ACS AEM Commons 6.0.0 all ACS COmmons service users (and their ACLs) were moved over to use RepoInit. 

I still am unsure how this would've happened w/ prior versions - but RepoInit is very good at ensuring all the users that should exist, do exist.
