### ISSUE TITLE
Issue with multifield

### ISSUE THREAD

**Issue by kdesineedi** [Adobe-Consulting-Services/acs-aem-commons#608] opened 2015-12-23 22:58 UTC
Drop Down values are not persisting on click of submit after we reopen the multified dialog
Also default value for drop down doesn't work.

There are no errors in the Javascript console as such.

![image](https://cloud.githubusercontent.com/assets/7786037/11986379/de820922-a99c-11e5-8e68-fc02734dfa80.png)

I have used the default value to be 'Open in Same Window' outside the multifield and it works.

Followed the steps as per the below link:
https://adobe-consulting-services.github.io/acs-aem-commons/features/widgets.html

Here is the dialog xml.

```

<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="cq:Dialog"
    height="400"
    title="ACSFooter"
    width="700"
    xtype="dialog">
    <items jcr:primaryType="cq:TabPanel">
        <items jcr:primaryType="cq:WidgetCollection">
            <text
                jcr:primaryType="cq:Widget"
                anchor="100%"
                title="Customer Service "
                xtype="panel">
                <items jcr:primaryType="cq:WidgetCollection">                   
                    <multilinks
                        jcr:primaryType="cq:Widget"
                        fieldLabel="custlinks"
                        name="./links"
                        xtype="multifield">
                        <fieldConfig
                            jcr:primaryType="cq:Widget"
                            xtype="multifieldpanel">
                            <items jcr:primaryType="cq:WidgetCollection">
                                <windowType
                                    jcr:primaryType="cq:Widget"
                                    boxMaxWidth="{Long}300"
                                    defaultValue="sameWindow"
                                    fieldLabel="windowTypeBehaviour"
                                    name="./windowType"
                                    type="select"
                                    xtype="selection">
                                    <options jcr:primaryType="cq:WidgetCollection">
                                        <sameWindow
                                            jcr:primaryType="nt:unstructured"
                                            text="Open in same window"
                                            value="sameWindow"/>
                                        <newWindow
                                            jcr:primaryType="nt:unstructured"
                                            text="Open in new window"
                                            value="newWindow"/>
                                        <newTab
                                            jcr:primaryType="nt:unstructured"
                                            text="Open in new Tab"
                                            value="newTab"/>
                                    </options>
                                </windowType>
                            </items>
                        </fieldConfig>
                    </multilinks>
                    <windowType
                        jcr:primaryType="cq:Widget"
                        boxMaxWidth="{Long}300"
                        defaultValue="sameWindow"
                        fieldLabel="windowTypeBehaviour"
                        name="./windowType1"
                        type="select"
                        xtype="selection">
                        <options jcr:primaryType="cq:WidgetCollection">
                            <sameWindow
                                jcr:primaryType="nt:unstructured"
                                text="Open in same window"
                                value="sameWindow"/>
                            <newWindow
                                jcr:primaryType="nt:unstructured"
                                text="Open in new window"
                                value="newWindow"/>
                            <newTab
                                jcr:primaryType="nt:unstructured"
                                text="Open in new Tab"
                                value="newTab"/>
                        </options>
                    </windowType>
                </items>
            </text>

        </items>
    </items>
</jcr:root>
```

**Comment by kdesineedi** [comment] 2016-01-27 19:28
Can anyone please provide inputs on this issue?

**Comment by chvankemseke** [comment] 2016-01-28 07:46
@kdesineedi I think this is a duplicate from [issue 477](https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/477)

**Comment by kdesineedi** [comment] 2016-01-29 20:31
Hi @chvankemseke Do you know which version of the ACS commons has this fix?

I am using 2.0.0

**Comment by justinedelson** [comment] 2016-01-31 13:10
If this is a duplicate of #477, that was fixed for version 2.2.0.

**Comment by kdesineedi** [comment] 2016-02-26 18:41
Hi @justinedelson ,so we took the latest version of ACS 2.3 and the issue is still persistent.

**Comment by stievena** [comment] 2016-12-20 14:40
Hi, the issue is also present on 3.5.2

**Comment by curtistadlock** [comment] 2017-03-15 18:05
There's a typo in the dialog.  You have name="./windowType" instead of key="windowType"

**Comment by davidjgonzalez** [comment] 2017-07-28 15:54
closing as this is in support of deprecated ClassicUI feature

**Closed by davidjgonzalez** 2017-07-28 15:54 UTC
Labels: closed due to lack of interest
