### ISSUE TITLE
AEM Environment Indicator truncate JSON output

### ISSUE THREAD

**Issue by maximenougarede** [Adobe-Consulting-Services/acs-aem-commons#2445] opened 2020-10-16 08:01 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6
* [ ] ACS AEM Commons Version: 4.8.4
* [ ] Reproducible on Latest? yes

### Expected Behavior

JSON output are not truncated (could even say that this filter should not execute on anything except html ?)

### Actual Behavior

When calling a JSON resource, the output is truncated.
e.g. calling .infinity.json will return a json ending as follow:

`"jcr:content":{"jcr:primaryT` 

No specific error logs.

### Steps to Reproduce

Install Assets 6.5.6
Install ACS AEM Commons 4.8.4
Configure Environment Indicator with values
Issue is intermittent and i didn't figure out yet the exact conditions.

### Links

http://localhost:4502/content/we-retail/language-masters/en.6.json JSON output is truncated
http://localhost:4502/content/we-retail/language-masters/en.5.json JSON output is complete

**Comment by kwin** [comment] 2020-10-16 09:02
This is most likely a duplicate of #2425

**Comment by badvision** [comment] 2020-10-19 18:46
#2425 fix is merged in, can we confirm this is resolved?

**Comment by maximenougarede** [comment] 2020-10-20 08:19
Hi @badvision,

**Comment by joerghoh** [comment] 2020-10-20 09:53
@maximenougarede thanks for the confirmation.

**Closed by joerghoh** 2020-10-20 09:53 UTC

**Comment by maximenougarede** [comment] 2020-10-20 15:25
Hi,

Do we know when version 4.8.8 will be released ?

Best regards,

**Comment by badvision** [comment] 2020-10-20 15:54
There's never a set release schedule, being a community project.  Having said that, within the week I hope.  There's some important fixes that I'm sure folks are itching to install, so it's on my radar.  At the same time, there are a few open issues related to recent improvements (such as reports) which I'd like to resolve if possible so we can ensure a high-quality release.
