### ISSUE TITLE
sitemap.xml issue

### ISSUE THREAD

**Issue by VasiRahman** [Adobe-Consulting-Services/acs-aem-commons#1758] opened 2019-02-19 09:42 UTC
## Required Information

* [ ] AEM Version - 6.4, including Service Packs, Cumulative Fix Packs - 6.4.2
* [ ] ACS AEM Commons Version: 3.17.0
* [ ] Reproducible on Latest? yes
* [ ] Currently 3 sites are running in one AEM server.  **mig.abc.com**, **mig.xyz.com**,**mig.mnp.com**

### Expected Behavior Sitemap.xml should be created in AEM as mentioned below.

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
    <loc>http://mig.xyz.com</loc>
    <lastmod>2018-11-23</lastmod>
</url>
<url>
    <loc>http://mig.xyz.com/login-page.html</loc>
    <lastmod>2018-11-29</lastmod>
</url>
<url>
    <loc>http://mig.xyz.com/signup-page.html</loc>
    <lastmod>2018-05-29</lastmod>
</url>
<url>
    <loc>http://mig.xyz.com/forgot-password-page.html</loc>
    <lastmod>2018-05-29</lastmod>
</url>

### Actual Behavior: First Url is taking from the second domain.

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
    <loc>http://mig.abc.com</loc>
    <lastmod>2018-11-23</lastmod>
</url>
<url>
    <loc>http://mig.xyz.com/login-page.html</loc>
    <lastmod>2018-11-29</lastmod>
</url>
<url>
    <loc>http://mig.xyz.com/signup-page.html</loc>
    <lastmod>2018-05-29</lastmod>
</url>
<url>
    <loc>http://mig.xyz.com/forgot-password-page.html</loc>
    <lastmod>2018-05-29</lastmod>
</url>

### Steps to Reproduce

Configure the ACS commons sitemap servlet.
![screenshot 2019-02-19 15 06 00](https://user-images.githubusercontent.com/13827678/53004905-1e33fa00-3458-11e9-8af1-99744ffba0d5.png)

etc map.publish Configurations:
![screenshot 2019-02-19 14 59 20](https://user-images.githubusercontent.com/13827678/53004976-415ea980-3458-11e9-99ba-aa6a780600b2.png)

**Comment by VasiRahman** [comment] 2019-02-20 05:13
> ## Required Information
> * [ ]  AEM Version - 6.4, including Service Packs, Cumulative Fix Packs - 6.4.2
> * [ ]  ACS AEM Commons Version: 3.17.0
> * [ ]  Reproducible on Latest? yes
> * [ ]  Currently 3 sites are running in one AEM server.  **mig.abc.com**, **mig.xyz.com**,**mig.mnp.com**
> 
> ### Expected Behavior Sitemap.xml should be created in AEM as mentioned below.
> http://mig.xyz.com 2018-11-23 http://mig.xyz.com/login-page.html 2018-11-29 http://mig.xyz.com/signup-page.html 2018-05-29 http://mig.xyz.com/forgot-password-page.html 2018-05-29
> ### Actual Behavior: First Url is taking from the second domain.
> http://mig.abc.com 2018-11-23 http://mig.xyz.com/login-page.html 2018-11-29 http://mig.xyz.com/signup-page.html 2018-05-29 http://mig.xyz.com/forgot-password-page.html 2018-05-29
> ### Steps to Reproduce
> Configure the ACS commons sitemap servlet.
> ![screenshot 2019-02-19 15 06 00](https://user-images.githubusercontent.com/13827678/53004905-1e33fa00-3458-11e9-8af1-99744ffba0d5.png)
> 
> etc map.publish Configurations:
> ![screenshot 2019-02-19 14 59 20](https://user-images.githubusercontent.com/13827678/53004976-415ea980-3458-11e9-99ba-aa6a780600b2.png)

**Comment by VasiRahman** [comment] 2019-03-11 06:30
Can someone reply to this?

**Comment by justinedelson** [comment] 2019-03-11 14:01
@VasiRahman I'm a bit doubtful that anyone could identify the problem based on the information you provided. That said, the sitemap servlet is not really doing much to generate these URLs. The actual URL generation is all happening in the `Externalizer`:

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/wcm/impl/SiteMapServlet.java#L245

So this is probably not really an issue with ACS AEM Commons but either an issue with your `/etc/map` configuration, your `Externalizer` configuration or a bug in the `Externalizer` itself (or some combination of these).

**Comment by davidjgonzalez** [comment] 2019-03-19 16:28
@VasiRahman closing per @justinedelson's response. 

Please re-open with info to reproduce and specifics as to how this is due to the ACS Commons implementation vs /etc/map or Externalizer config. Thanks!

**Closed by davidjgonzalez** 2019-03-19 16:28 UTC
Labels: invalid, need more info

**Comment by neeniya** [comment] 2019-08-13 04:20
@VasiRahman were you able to solve this issue? I believe I am encountering the same thing with my  sitemap. I invoked the Externalizer.externalLink() method elsewhere in my project to test if it was a bug in the externalizer, and got the correct URL mapping.
