### ISSUE TITLE
Touch ui limit parsys issue: Granite.author is undefined

### ISSUE THREAD

**Issue by adolfodepazvela** [Adobe-Consulting-Services/acs-aem-commons#950] opened 2017-04-03 20:20 UTC
Hi

I still getting this issue on sites.html when Page Properties is open, this error causing other issues on IE11.
Even after applying the fix proposed in #677

Uncaught TypeError: Cannot read property 'dropController' of undefined

Thanks

**Comment by justinedelson** [comment] 2017-04-06 11:19
What version of ACS AEM Commons are you using? What version of AEM?

I really don't see how this is possible with the current versions.

**Comment by adolfodepazvela** [comment] 2017-04-06 13:20
Hi Justin,

I use AEM 6.1 +  SP2, the ACS Commons version is 2.3

I fixed temporally by adding above code in the header of
extendComponentDrop function of the following
file: /apps/acs-commons/touchui-widgets/source/touchui-limit-parsys.js

*if (gAuthor == undefined) {*

* return;*

*}*

This JS error only happens when you open the pageProperties in the Admin
console.

Thanks

Adolfo

**Comment by justinedelson** [comment] 2017-04-06 13:31
This issue was fixed in 2.5.0, although I see the issue did not have a milestone set on it (which has since been corrected).

If this is reproducible with 2.7.0, please reopen.

**Closed by justinedelson** 2017-04-06 13:31 UTC
