### ISSUE TITLE
MCP Processes are not visible when starting a process in MCP console

### ISSUE THREAD

**Issue by mranjandube** [Adobe-Consulting-Services/acs-aem-commons#2755] opened 2021-12-07 09:48 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: __6.5.0,6.5.9_____
* [ ] ACS AEM Commons Version: __5.0.4___
* [ ] Reproducible on Latest? yes

### Expected Behavior

Whenever I am accessing the MCP console through IP and start a process, new process entry is getting created on MCP console. Similarly whenever I do the same through domain instead of IP same functionality should work.  

### Actual Behavior

Whenever I am accessing the MCP console through domain and create a process, new entry is not getting created, even though in BE the functionality is working as expected. 

### Steps to Reproduce

Tools -> AEM ACS Commons -> MCP
Click on process
No entry is getting created but in BE functionality is working as expected.

**Comment by YegorKozlov** [comment] 2021-12-07 11:58
Duplicate of #2749

**Closed** 2022-05-05 14:39 UTC
