### ISSUE TITLE
MCP Asset Folder Creator Fails on AEM 6.5 SP3

### ISSUE THREAD

**Issue by shsteimer** [Adobe-Consulting-Services/acs-aem-commons#2162] opened 2020-01-15 18:27 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc:6.5.3.0
* [ ] ACS AEM Commons Version: 4.4.0
* [ ] Reproducible on Latest? yes

### Expected Behavior

The folders should be created successfully without an error

### Actual Behavior

No folders are created, the following stack trace is produced, pointing to a no such method error when calling POI.

```
java.lang.RuntimeException: java.lang.NoSuchMethodError: 
org.apache.poi.ss.usermodel.Cell.setCellType(I)V at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:175) at 
com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159) at 
com.adobe.acs.commons.fam.impl.ActionManagerImpl$$Lambda$339/1098834023.run(Unknown Source) at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91) at 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at 
java.util.concurrent.FutureTask.run(FutureTask.java:266) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at 
java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.setCellType(I)V at 
com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator.parseAssetFolderCell(AssetFolderCreator.java:189) at 
com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator.parseAssetFolderRow(AssetFolderCreator.java:170) at 
com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator.lambda$parseAssetFolderDefinitions$0(AssetFolderCreator.java:151) at 
com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator$$Lambda$342/335134771.accept(Unknown Source) at 
com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200) at 
com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator.parseAssetFolderDefinitions(AssetFolderCreator.java:142) at 
com.adobe.acs.commons.mcp.impl.processes.AssetFolderCreator$$Lambda$315/1643962007.accept(Unknown Source) at
com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl.lambda$runStep$14(ProcessInstanceImpl.java:236) at 
 com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl$$Lambda$338/1654569062.accept(Unknown Source) at
  com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200) at 
```

### Steps to Reproduce

Run the mcp asset folder creator tool with any compatible excel sheet.

### Links

_Links to related assets, e.g. content packages containing test components_

In the only java doc I can find online for the relevant POI class, http://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/Cell.html#setCellType-org.apache.poi.ss.usermodel.CellType-, it says that method is deprecated and will be removed in 5.0.  Strangely, the POI bundle used by AEM appears to export 3.0.0, so I'm not 100% sure what is going on there, but the issue is readily reproducible under SP3.  My guess is that the service pack updated the POI bundle for some reason, thus causing the no such method error.

**Comment by badvision** [comment] 2020-01-15 19:47
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/c2eef196a57762b4e01d04a8aaf203e2b7c32003/bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/AssetFolderCreator.java#L189

The awkward thing about this bug is that the CellType enum doesn't exist until version 3.15 so we can't switch our code reliably over to that and expect things to compile or even bind correctly in older versions of AEM that use v3.0 and not a newer 3.x version of the library.  Our choices are then limited to 1) Code that uses reflection to bypass version compatibility limitations (which is ugly but can work in theory) or 2) Remove that line of code which will revert the bug it fixed in the first place via #1791

**Comment by badvision** [comment] 2020-01-15 19:48
@davidjgonzalez, @justinedelson thoughts on this one?

**Comment by davidjgonzalez** [comment] 2020-01-15 20:02
perhaps this might be a work around?

http://apache-poi.1045710.n5.nabble.com/How-to-set-Cell-Format-to-Text-tp3275568p3275966.html

It's not obvious to me how `setCellValue(..)` is a reasonable replacement, since IIRC, getting the value (which youd have to do to reset it) was what's breaking before .. and if you can get it as a String, there would be no point to resetting it anyhow.

**Comment by badvision** [comment] 2020-01-15 20:05
That is rather strange but I've seen stranger.  If we have unit test coverage of #1791 can we try this to see if it doesn't result in a regression?

**Comment by slreynol** [comment] 2020-01-30 20:31
possibly try 
https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/Cell.html#setCellFormula-java.lang.String- to replace the deprecated setCellType?

**Comment by badvision** [comment] 2020-01-30 20:46
I have a solution in place -- I just get the type as an object and then convert to an internal version of the enumeration they introduced in POI 4.  That way it works the same with new and old versions.  Fortunately there were no other significant impacts in the version changes of POI that we could find.

**Comment by badvision** [comment] 2020-01-30 20:46
The problem with using other methods to coerce the value type is that you are relying on undocumented side effects and that's more fragile overall.

**Closed** 2020-02-29 17:15 UTC
