### ISSUE TITLE
Workflow removed removing workflow instances newer than passed date

### ISSUE THREAD

**Issue by tb7032** [Adobe-Consulting-Services/acs-aem-commons#1528] opened 2018-10-30 11:06 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _AEM 6.3 / AEM 6.4___
* [ ] ACS AEM Commons Version: __3.17___
* [ ] Reproducible on Latest? yes

*### Expected Behavior*

Workflow remover should respect the 'Workflows older than' argument when deleting running workflow instances.

*### Actual Behavior*

Workflow instances newer than the passed date appear to get deleted.

*### Steps to Reproduce*

* Start clean AEM 6.3 / 6.4
* Install latest ACS Commons 
* Start a couple of workflows that will stay in running state - ie a couple of Request For Activation worklfows (against any pages or assets).
* Confirm that the workflows are visible and showing as running in the workflow console
* Open workflow remover and select to remove:
** *Status:* Running
** *Workflows older than:* any date before the date the workflows started above (ie 72 hours ago
* Click 'Remove Workflows'
* Refresh workflow console and notice that the workflows started above were removed, despite apparently not meeting the passed criteria.

### Links

n/a

**Comment by vaibhav6451956** [comment] 2019-01-19 17:09
@davidjgonzalez  @justinedelson  I am also facing this. Can you please help here? All the workflow instances get removed without respecting **Workflows older than** criteria.

**Comment by vaibhav6451956** [comment] 2019-01-22 11:59
@davidjgonzalez   In the meantime, can you please point me to the code so that I can debug and try to add an intermediate fix?

**Comment by spauwels** [comment] 2019-03-18 10:49
I, also get this bug.
I guess the problem is here 
https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/acs-aem-commons-3.19.0/bundle/src/main/java/com/adobe/acs/commons/workflow/bulk/removal/impl/WorkflowInstanceRemoverImpl.java****
line 279
 `final Calendar startTime = properties.get(PN_STARTED_AT, Calendar.class);`
`PN_STARTED_AT` has to be `startTime`

**Comment by davidjgonzalez** [comment] 2019-03-19 00:50
This should be fixed via: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1793

**Closed** 2019-10-16 22:06 UTC
Labels: bug, pinned
