### ISSUE TITLE
Dynamic Deck Dynamo tool is not working

### ISSUE THREAD

**Issue by YahorPronski** [Adobe-Consulting-Services/acs-aem-commons#2830] opened 2022-04-26 07:27 UTC
## Required Information

* [1] AEM Version, including Service Packs, Cumulative Fix Packs, etc: **6.5.0&6.5.12**
* [2] ACS AEM Commons Version: **5.3.0**
* [3] Reproducible on Latest? **yes**

### Expected Behavior

Dynamic Deck Dynamo tool should be displayed without errors.

### Actual Behavior

On open Dynamic Deck Dynamo on clean AEM 6.5.0 instance I see the next:
![ddi_error1](https://user-images.githubusercontent.com/73655118/165244292-c1228782-b8c9-4aa6-8072-effff5a34fcc.png)

On AEM 6.5.12:
![ddi_error2](https://user-images.githubusercontent.com/73655118/165244405-58fb82c9-03ae-42d2-8e9f-083cb4431af7.png)

**Comment by davidjgonzalez** [comment] 2022-05-02 18:15
You can work around this by adding at least 1 item to the dynamic deck Generic List page (you can even remove that item after adding) - the problem is if a gneric list doesnt have an `jcr:content/list` subnode things start getting returned as null.

**Comment by davidjgonzalez** [comment] 2022-05-02 18:23
This is fixed via:

![2022-05-02 at 2 23 PM](https://user-images.githubusercontent.com/1451868/166303414-c9adfbcd-3172-4553-a8c4-79ee424e6041.jpg)

**Closed** 2022-07-22 15:27 UTC
Labels: bug
