### ISSUE TITLE
encoding issue for special characters in error page

### ISSUE THREAD

**Issue by SrinivasChannappa** [Adobe-Consulting-Services/acs-aem-commons#482] opened 2015-07-15 06:56 UTC
I am using the below error handler for 404 page

/apps/project/config.publish/com.adobe.acs.commons.errorpagehandler.impl.ErrorPageHandlerImpl

jcr:primaryType Name    sling:OsgiConfig  
cache.serve-authenticated   Boolean true  
cache.ttl   Long    300 
enabled Boolean true  
error-page.system-path  String  /content/website/404  
not-found.behavior  String  respond-with-404

works:-
When i hit an nonexistent  page 

say http://localhost:4503/content/geometrixx-outdoors/dd.html

it goes to the  error page /content/website/404 and here special chararctes 

come up ® correctly on the page

Problem:-

When i hit an nonexistent  page  without extension ".html"

say http://localhost:4503/content/geometrixx-outdoors/dd

it goes to the  error page /content/website/404 and here special chararctes  comes up as � instead of ® .

Please let me know how to solve the problem

Thanks

**Comment by davidjgonzalez** [comment] 2015-07-15 13:43
Can you provide screenshots of the 404 being served through the error handler and then a screen shot of the 404 page being opened directly?

Also - what character encoding is used to create your special char?

**Comment by SrinivasChannappa** [comment] 2015-07-16 14:41
![error_page1](https://cloud.githubusercontent.com/assets/13345575/8726252/adbd776e-2bf6-11e5-9c0e-e222e81002d5.png)
![page2](https://cloud.githubusercontent.com/assets/13345575/8726260/bb2f7528-2bf6-11e5-8b64-d55bdb444d04.png)

using 


DeSolite® 

CakeZyme®

**Comment by davidjgonzalez** [comment] 2015-09-12 00:46
I dropped in your

DeSolite®
CakeZyme®

into a 404 page it they render fine..  are you using some sort of funky char encoding perhaps?

Can you save and upload the actual HTML output that is being represented incorrectly?

![2015-09-11 at 8 44 pm](https://cloud.githubusercontent.com/assets/1451868/9829062/0db281f4-58c6-11e5-8cb5-4a81eaf1795c.png)

**Comment by davidjgonzalez** [comment] 2015-12-15 05:08
Cannot reproduce and issue was not followed up.

**Comment by SrinivasChannappa** [comment] 2015-12-15 06:54
Sorry i did not know  you need more  information. The actual page where you could find the error is http://www.dsm.com/corporate/about/home

**Comment by davidjgonzalez** [comment] 2017-07-29 19:03
Closing as i believe this is a duplicate of: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1010

**Closed by davidjgonzalez** 2017-07-29 19:03 UTC
Labels: bug, help wanted
