### ISSUE TITLE
Sling/Granite Content Access Check fails on AEM 6.5.3

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Consulting-Services/acs-aem-commons#2201] opened 2020-02-26 11:05 UTC
Sling/Granite Content Access Check
--
```
Tags: [repository, sling] Finished: 2020-02-26 00:00 after 724msResult: WARN
WARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/cq:editConfig overrides INTERNAL path /libs/cq/flow/components/step/step/cq:editConfig which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/cq:editConfig/cq:formParameters overrides INTERNAL path /libs/cq/flow/components/step/step/cq:editConfig which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/dialog overrides INTERNAL path /libs/cq/flow/components/step/step/dialog which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/dialog/items overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/dialog/items/tabs overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items/tabs which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/dialog/items/tabs/items overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items/tabs/items which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/dialog/items/tabs/items/processcommon overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items/tabs/items which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/dialog/items/tabs/items/processargs overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items/tabs/items which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/processargs overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/processargs/items overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/processargs/items/arguments overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/watson-audio-transcription/processargs/items/arguments/items overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/agentoptions.json.jsp overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/agentoptions.json.jsp/jcr:content overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/deactivate overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/deactivate/cq:editConfig overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/deactivate/cq:editConfig/cq:formParameters overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/deactivate/cq:editConfig/cq:listeners overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/dialog overrides INTERNAL path /libs/cq/flow/components/step/step/dialog which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/dialog/items overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/dialog/items/tabs overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items/tabs which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/dialog/items/tabs/items overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items/tabs/items which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/dialog/items/tabs/items/processcommon overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items/tabs/items which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/dialog/items/tabs/items/processargs overrides INTERNAL path /libs/cq/flow/components/step/step/dialog/items/tabs/items which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/processargs overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/processargs/items overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/processargs/items/arguments overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/processargs/items/arguments/items overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/processargs/items/arguments/items/agentToUse overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/cache-invalidate overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/cache-invalidate/cq:editConfig overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/cache-invalidate/cq:editConfig/cq:formParameters overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/cache-invalidate/cq:editConfig/cq:listeners overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/activate overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/activate/cq:editConfig overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/activate/cq:editConfig/cq:formParameters overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/workflow/select-agent/activate/cq:editConfig/cq:listeners overrides INTERNAL path /libs/cq/flow/components/step/step which is classified as INTERNAL at /libs/cq/flowWARN The resource /apps/acs-commons/components/authoring/graphiciconselect overrides FINAL resource super type granite/ui/components/foundation/form/select which is classified as FINAL at /libs/granite/ui/components/foundation/form/selectWARN The resource /apps/acs-commons/components/authoring/graphiciconselect/render.jsp overrides INTERNAL path /libs/granite/ui/components/foundation/form/select/render.jsp which is classified as FINAL at /libs/granite/ui/components/foundation/form/selectWARN The resource /apps/acs-commons/components/authoring/graphiciconselect/render.jsp/jcr:content overrides INTERNAL path /libs/granite/ui/components/foundation/form/select/render.jsp/jcr:content which is classified as FINAL at /libs/granite/ui/components/foundation/form/selectWARN The resource /apps/acs-commons/touchui-widgets/contextualpathbrowser overrides FINAL resource super type granite/ui/components/foundation/form/pathbrowser which is classified as FINAL at /libs/granite/ui/components/foundation/form/pathbrowserWARN The resource /apps/acs-commons/touchui-widgets/contextualpathbrowser/contextualpathbrowser.jsp overrides FINAL path /libs/granite/ui/components/foundation/form/pathbrowser which is classified as FINAL at /libs/granite/ui/components/foundation/form/pathbrowserWARN The resource /apps/acs-commons/touchui-widgets/contextualpathbrowser/contextualpathbrowser.jsp/jcr:content overrides FINAL path /libs/granite/ui/components/foundation/form/pathbrowser which is classified as FINAL at /libs/granite/ui/components/foundation/form/pathbrowser
```

**Comment by davidjgonzalez** [comment] 2020-03-25 21:32
@henrykuijpers these are from the AEM Pattern Detector correct?

**Comment by henrykuijpers** [comment] 2020-03-25 21:37
@davidjgonzalez No, they are from the Sling/Granite content access health check that you can see in the health operations dashboard. 

For us it's annoying that they're failing due to acs aem commons, because the category (tag) of that health check is "sling". In that category, there are some other very very useful healthchecks, that we would like to use in our cloud setup. 

You can see the failures in the dashboard in the aem interface, or through the OSGi console, there's a section that is able to show the content access health check results as well.

**Comment by sabarishreddy** [comment] 2020-07-16 07:47
was there any change in priorities in fixing this issue?

**Comment by kwin** [comment] 2020-07-16 08:09
This is a duplicate of #1511

**Closed by kwin** 2020-07-16 08:09 UTC
Labels: bug, duplicate

**Comment by kwin** [comment] 2020-07-16 08:14
I think this a false positive though as the direct super type is `/libs/cq/workflow/components/model/external_process` which is marked as `granite:PublicArea`. Only its supertype is protected. @sabarishreddy Please raise that as ticket with the AEM Product Support.
