### ISSUE TITLE
Email Service Subject mangled when non-latin chars are provided

### ISSUE THREAD

**Issue by heyonghan** [Adobe-Consulting-Services/acs-aem-commons#1008] opened 2017-05-23 03:28 UTC
I create a Japanese email template(define the Sendto,CC,subject,Body) and use the ACS common Email API to send it.
When the email subject contains Japanese. The subject became messy code when I receive it. No problem in body part.

**Comment by davidjgonzalez** [comment] 2017-06-09 19:14
@heyonghan is this a problem still? IIRC you provide the subject in the same manner to the template as the, via the same map, so this might be something in the Apache Email library? Have you checked their jira/issues?

Also, if you set the Subject text in the body as well, i assume you see that it errs in the Subject, but NOT the body? (trying to verify that there is nothing funny w how the subject is being created to begin with and the issue is downstream from the String definition)

**Comment by davidjgonzalez** [comment] 2017-07-28 14:24
Fix merged

**Closed** 2017-07-28 14:24 UTC
Labels: bug
