### ISSUE TITLE
Unable to add new pages under Classic UI Consoles

### ISSUE THREAD

**Issue by reggie7** [Adobe-Consulting-Services/acs-aem-commons#1832] opened 2019-04-12 11:59 UTC
* [ ] `AEM 6.5`
* [ ] ACS AEM Commons Version: `4.0.0`
* [ ] Reproducible on Latest? **yes**

### Expected Behavior

When I open any `Classic UI` based Console pointing me to [Tools](http://localhost:4502/miscadmin),

![Screenshot_1](https://user-images.githubusercontent.com/5563546/56035365-3d4d5a80-5d2a-11e9-86c0-06efc80c0796.png)

I'd expect to be able to add appropriate pages underneath the [given folder](http://localhost:4502/miscadmin#/etc/acs-commons/bulk-workflow-manager):

![correct](https://user-images.githubusercontent.com/5563546/56035426-71288000-5d2a-11e9-84dc-c51f0b789a85.png)

### Actual Behavior

I get the following disabled UI:

![incorrect](https://user-images.githubusercontent.com/5563546/56035484-9ae1a700-5d2a-11e9-9cc6-07553a7cc49b.png)

### Steps to Reproduce

Open any `Classic UI` based Console:

- [Automatic Page Replication](http://localhost:4502/miscadmin#/etc/acs-commons/automatic-package-replication)
- [Dispatcher Flush](http://localhost:4502/miscadmin#/etc/acs-commons/dispatcher-flush)
- [Redirect Maps](http://localhost:4502/miscadmin#/etc/acs-commons/redirect-maps)
- [Bulk Workflow Manager](http://localhost:4502/miscadmin#/etc/acs-commons/bulk-workflow-manager)
- [Users to CSV Exporter](http://localhost:4502/miscadmin#/etc/acs-commons/exporters)
- [System Notifications](http://localhost:4502/miscadmin#/etc/acs-commons/notifications)
- [Content Packagers](http://localhost:4502/miscadmin#/etc/acs-commons/packagers)

Try to add a new page. It will be unavailable.

### Workaround

There is a workaround for the above behaviour:
- Click any other element in the left hand side tree,
- Go back to your original folder.

Now all will work as expected.

### Remarks

The bug might come from `AEM`, not necessarily `ACS AEM Commons`.

**Comment by davidjgonzalez** [comment] 2019-04-19 17:56
reproduced this... it looks like its an artifact of directly "opening" a folder in miscadmin .. 

clicking on another folder, and then back allows new pages to be created.

for example,  opening the following URL (ootb console) http://localhost:4502/miscadmin#/etc/mobile
has the same effect.

..closing as won't fix as this is an AEM issue, though certainly unfortunate UX for us.

**Closed by davidjgonzalez** 2019-04-19 17:56 UTC

**Comment by reggie7** [comment] 2019-04-23 10:02
Sure. Shall it be reported/fixed in AEM then? Or rather skipped (as the Classic UI is going out of the picture)?
