### ISSUE TITLE
i18n Sling Models Injector causes very poor performance for AEM Forms Adaptive Forms

### ISSUE THREAD

**Issue by blackfor** [Adobe-Consulting-Services/acs-aem-commons#1881] opened 2019-05-06 21:54 UTC
## Required Information

* AEM Version : 6.4.4.0
* ACS AEM Commons Version: 4.0.0

### Actual Behavior

The New i18n injector (see [1]) causes very poor performance for AEM Forms Adaptive Forms. 

When this is present, the peformance of POST requests to FORMs decreases massively - with the CPU time being spent apparently in logging. 

As soon as the component 'com.adobe.acs.commons.models.injectors.impl.I18nInjector' is disabled, normal performance returns.

When the component is enabled, thread dumps show all POSTs to adaptive forms queueing up in the method, like so: 

`"10.43.0.96 [1557172281638] POST /content/forms/af/tg-claims/direct/us/status/jcr:content/guideContainer.af.dermis HTTP/1.1" #47559 prio=5 os_prio=0 tid=0x00007f1a3010c000 nid=0x7746 waiting on condition [0x00007f1a04590000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000072527f518> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at ch.qos.logback.core.OutputStreamAppender.writeBytes(OutputStreamAppender.java:197)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:231)
	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:235)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
	at ch.qos.logback.classic.Logger.debug(Logger.java:486)
	at org.apache.sling.i18n.impl.JcrResourceBundleProvider.getResourceBundleInternal(JcrResourceBundleProvider.java:442)
	at org.apache.sling.i18n.impl.JcrResourceBundleProvider.getResourceBundle(JcrResourceBundleProvider.java:200)
	at org.apache.sling.i18n.impl.JcrResourceBundleProvider.getResourceBundle(JcrResourceBundleProvider.java:191)
	at com.adobe.acs.commons.i18n.impl.I18nProviderImpl.getResourceBundle(I18nProviderImpl.java:160)
	at com.adobe.acs.commons.i18n.impl.I18nProviderImpl.getResourceBundleFromPageLocale(I18nProviderImpl.java:147)
	at com.adobe.acs.commons.i18n.impl.I18nProviderImpl.i18n(I18nProviderImpl.java:129)
	at com.adobe.acs.commons.models.injectors.impl.I18nInjector.getValue(I18nInjector.java:77)
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:593)
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:744)
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:448)
	at org.apache.sling.models.impl.ModelAdapterFactory.adapt(ModelAdapterFactory.java:1063)
	at org.apache.sling.models.impl.ModelAdapterFactory.adaptIfNecessary(ModelAdapterFactory.java:1031)
	at org.apache.sling.models.impl.ModelAdapterFactory.setField(ModelAdapterFactory.java:987)
	at org.apache.sling.models.impl.ModelAdapterFactory.access$200(ModelAdapterFactory.java:132)
	at org.apache.sling.models.impl.ModelAdapterFactory$SetFieldCallback.inject(ModelAdapterFactory.java:500)
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:595)
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:744)
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:448)
	at org.apache.sling.models.impl.ModelAdapterFactory.adapt(ModelAdapterFactory.java:1063)
	at org.apache.sling.models.impl.ModelAdapterFactory.adaptIfNecessary(ModelAdapterFactory.java:1031)
	at org.apache.sling.models.impl.ModelAdapterFactory.setField(ModelAdapterFactory.java:987)
	at org.apache.sling.models.impl.ModelAdapterFactory.access$200(ModelAdapterFactory.java:132)
	at org.apache.sling.models.impl.ModelAdapterFactory$SetFieldCallback.inject(ModelAdapterFactory.java:500)
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:595)
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:744)
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:448)
	at org.apache.sling.models.impl.ModelAdapterFactory.adapt(ModelAdapterFactory.java:1063)
	at org.apache.sling.models.impl.ModelAdapterFactory.adaptIfNecessary(ModelAdapterFactory.java:1044)
	at org.apache.sling.models.impl.ModelAdapterFactory.setField(ModelAdapterFactory.java:987)
	at org.apache.sling.models.impl.ModelAdapterFactory.access$200(ModelAdapterFactory.java:132)
	at org.apache.sling.models.impl.ModelAdapterFactory$SetFieldCallback.inject(ModelAdapterFactory.java:500)
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:595)
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:744)
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:448)
	at org.apache.sling.models.impl.ModelAdapterFactory.getAdapter(ModelAdapterFactory.java:302)
	at org.apache.sling.adapter.internal.AdapterManagerImpl.getAdapter(AdapterManagerImpl.java:143)
	at org.apache.sling.api.adapter.SlingAdaptable.adaptTo(SlingAdaptable.java:104)
	- locked <0x000000077920c038> (a org.apache.sling.jcr.resource.internal.helper.jcr.JcrNodeResource)
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrNodeResource.adaptTo(JcrNodeResource.java:156)
	at com.adobe.aem.dermis.core.service.slingmodel.FormDataModelManager.getFormDataModelDAMAsset(FormDataModelManager.java:233`

Turning on DEBUG level logging showed over four thousand DEBUG messages like the one below (complete with stack trace) for a single POST request. It appears to be volume of these DEBUG level messages that is proving a performance bottleneck.

`
06.05.2019 13:45:33.135 *DEBUG* [10.43.0.96 [1557175524697] POST /content/forms/af/tg-claims/myclaim/us/status/jcr:content/guideContainer.af.dermis HTTP/1.1] org.apache.sling.models.impl.ModelAdapterFactory Injection into optional element private java.lang.String co
m.adobe.aem.dermis.slingmodel.TypeAssetModel.mediaType failed because of: Could not adapt from class com.day.cq.i18n.I18n to class java.lang.String, because this class is not adaptable!
org.apache.sling.models.factory.ModelClassException: Could not adapt from class com.day.cq.i18n.I18n to class java.lang.String, because this class is not adaptable!
	at org.apache.sling.models.impl.ModelAdapterFactory.adapt(ModelAdapterFactory.java:1081) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.adaptIfNecessary(ModelAdapterFactory.java:1044) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.setField(ModelAdapterFactory.java:987) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.access$200(ModelAdapterFactory.java:132) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory$SetFieldCallback.inject(ModelAdapterFactory.java:500) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:595) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:744) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:448) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.adapt(ModelAdapterFactory.java:1063) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.adaptIfNecessary(ModelAdapterFactory.java:1031) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.setField(ModelAdapterFactory.java:987) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.access$200(ModelAdapterFactory.java:132) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory$SetFieldCallback.inject(ModelAdapterFactory.java:500) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:595) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:744) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:448) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.adapt(ModelAdapterFactory.java:1063) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.adaptIfNecessary(ModelAdapterFactory.java:1031) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.setField(ModelAdapterFactory.java:987) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.access$200(ModelAdapterFactory.java:132) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory$SetFieldCallback.inject(ModelAdapterFactory.java:500) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:595) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:744) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:448) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.adapt(ModelAdapterFactory.java:1063) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.adaptIfNecessary(ModelAdapterFactory.java:1044) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.setField(ModelAdapterFactory.java:987) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.access$200(ModelAdapterFactory.java:132) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory$SetFieldCallback.inject(ModelAdapterFactory.java:500) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:595) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:744) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:448) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.models.impl.ModelAdapterFactory.getAdapter(ModelAdapterFactory.java:302) [org.apache.sling.models.impl:1.4.10]
	at org.apache.sling.adapter.internal.AdapterManagerImpl.getAdapter(AdapterManagerImpl.java:143) [org.apache.sling.adapter:2.1.10]
`

### Steps to Reproduce

* Run AEM Forms Adaptive forms with ACS Commons 4.0.0
* Turn on DEBUG level logging on Sling Models to see the exception.

### Links

[1] https://adobe-consulting-services.github.io/acs-aem-commons/features/sling-model-injectors/i18n/index.html

**Comment by justinedelson** [comment] 2019-05-07 14:15
I'm not 100% sure, but I believe the problem is that `ReflectionUtil.isAssignableFrom` is always returning `true`.

As seen in the thread dump, line 77 of https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/models/injectors/impl/I18nInjector.java#L77 is being invoked. The only time this _should_ happen is if the injection point target is of type `com.day.cq.i18n.I18n`. However, due to the bug in `ReflectionUtil` this is happening all the time (unless the injection point is annotated with `com.adobe.acs.commons.models.injectors.annotation.I18N`, which is unlikely for AEM product code, and the injection point target is a `java.lang.String`).

**Comment by niekraaijmakers** [comment] 2019-05-07 15:32
I believe your right Justin. Auch. I will at any rate also add an annotation present check for the Object as well to narrow this down at any rate. I'll see what I can do here. Thanks for finding out this bug.

**Comment by justinedelson** [comment] 2019-05-07 15:38
@niekraaijmakers I don't think that's necessary.

I would think that

```
@Inject private I18n i18n;
```

is sufficient declaration of intent.

**Comment by justinedelson** [comment] 2019-05-07 15:39
@blackfor I'm going to close this under the assumption that the fix in #1883 fixes the problem. Feel free to reopen after testing if that proves to not be the case.

**Closed by justinedelson** 2019-05-07 15:39 UTC
Labels: bug
