### ISSUE TITLE
Issue in ACS commons report : unable to get all metadata and jcr values. 

### ISSUE THREAD

**Issue by MdAzzaruddin9254** [Adobe-Consulting-Services/acs-aem-commons#2865] opened 2022-06-21 05:46 UTC
## Required Information

* [ ] AEM Version, including Service Packs, : **6.5 , service pack 6.5.10**
* [ ] ACS AEM Commons Version: **5.3.0**
* [ ] Reproducible on Latest? **Yes**

### Expected Behavior
Report should be able to display all columns with values and should be able to download the same 

### Actual Behavior

Report is throwing this exception "Exception executing report: org.apache.sling.api.scripting.ScriptEvaluationException:"

### Steps to Reproduce
Step 1 : Upload the ACS reports package given below and check for the report "All Asset Report" in the reports list "http://localhost:4502/apps/acs-commons/content/reports.html"
Step 2:  Execute the report 
Step 3 : We are getting this error "Exception executing report: org.apache.sling.api.scripting.ScriptEvaluationException:"
Step 4: check for attached error log file below.

### Links

[all assets reports-1.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/8946119/all.assets.reports-1.zip)
[error-log.txt](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/8946122/error-log.txt)

**Comment by davidjgonzalez** [comment] 2022-06-22 16:09
@MdAzzaruddin9254 the problem is your Report config is using absolute path for columns. Change your paths from `/jcr:content/...` to just `jcr:content/...`

I'll add PR a safety catch (that removed leading `/` if theyre accidently added for the next release, but you can fix this one yourself now by just updating those paths in the report def)

![2022-06-22 at 12 06 PM](https://user-images.githubusercontent.com/1451868/175080042-970ca3fa-c206-425e-afa9-94614846a5b3.jpg)

Also, thanks for including the repo definition! it made it so much easier to see whats going on!

**Comment by davidjgonzalez** [comment] 2022-06-22 22:25
Fixed in 5.3.2

**Closed by davidjgonzalez** 2022-06-22 22:25 UTC
Labels: technical enhancement
