### ISSUE TITLE
Bulk Workflow Manager is not working

### ISSUE THREAD

**Issue by ayfengl** [Adobe-Consulting-Services/acs-aem-commons#1300] opened 2018-04-02 05:34 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.4 
* [ ] ACS AEM Commons Version: 3.14.10
* [ ] Reproducible on Latest? Yes

Trying to use the bulk workflow manager and when selecting the AEM workflow to use the DAM Update Asset, the 'Start Workflow' button at the end is not enabled after inputting all the information.

I believe the 'Start Workflow' should be enabled.

Also tried to use the 'Synthetic Workflow', the 'Start Workflow' is enabled. 
However it doesn't run.  When I looked at AEM I see this error message:
02.04.2018 05:25:49.991 *ERROR* [192.150.10.213 [1522646749894] POST /etc/acs-commons/bulk-workflow-manager/AMS/_jcr_content.start.json HTTP/1.1] com.adobe.granite.workflow.core.jcr.WorkflowModelManager Failed to check for the existance of a overlaid workflow model with ID /var/workflow/models//var/workflow/models/dam/update_asset, continuing with original model ID /etc/workflow/models//var/workflow/models/dam/update_asset/jcr:content/model
	at com.adobe.acs.commons.workflow.bulk.execution.impl.runners.FastActionManagerRunnerImpl$FastActionManagerRunnable.run(FastActionManagerRunnerImpl.java:230) [com.adobe.acs.acs-aem-commons-bundle:3.14.10]
	at com.adobe.acs.commons.workflow.bulk.execution.impl.BulkWorkflowEngineImpl.start(BulkWorkflowEngineImpl.java:96) [com.adobe.acs.acs-aem-commons-bundle:3.14.10]
	at com.adobe.acs.commons.workflow.bulk.execution.impl.servlets.StartServlet.doPost(StartServlet.java:106) [com.adobe.acs.acs-aem-commons-bundle:3.14.10]
02.04.2018 05:25:49.991 *ERROR* [192.150.10.213 [1522646749894] POST /etc/acs-commons/bulk-workflow-manager/AMS/_jcr_content.start.json HTTP/1.1] com.adobe.acs.commons.workflow.bulk.execution.impl.servlets.StartServlet Could not initialize Bulk Workflow due to unexpected error: {}
	at com.adobe.acs.commons.workflow.bulk.execution.impl.runners.FastActionManagerRunnerImpl$FastActionManagerRunnable.run(FastActionManagerRunnerImpl.java:230) [com.adobe.acs.acs-aem-commons-bundle:3.14.10]
	at com.adobe.acs.commons.workflow.bulk.execution.impl.BulkWorkflowEngineImpl.start(BulkWorkflowEngineImpl.java:96) [com.adobe.acs.acs-aem-commons-bundle:3.14.10]
	at com.adobe.acs.commons.workflow.bulk.execution.impl.servlets.StartServlet.doPost(StartServlet.java:106) [com.adobe.acs.acs-aem-commons-bundle:3.14.10]

**Comment by justinedelson** [comment] 2018-04-02 15:36
@davidjgonzalez can you take a look at this?

**Comment by badvision** [comment] 2018-04-02 23:18
This is a duplicate of #1276 -- closing (and yes, we need to fix this -- no workflows seem to work in 6.4 because it no longer uses relative paths or something like that)

**Closed by badvision** 2018-04-02 23:18 UTC
