### ISSUE TITLE
bind/unbind method not found on AEM 6.1

### ISSUE THREAD

**Issue by mstkymmt** [Adobe-Consulting-Services/acs-aem-commons#784] opened 2016-08-24 13:17 UTC
I got the following error when the com.adobe.acs.acs-aem-commons-bundle was activated.

```
24.08.2016 22:04:19.746 *INFO* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle Service [com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess,7285, [com.day.cq.workflow.exec.WorkflowProcess]] ServiceEvent REGISTERED
24.08.2016 22:04:19.747 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(3816)] bind method [bindWcmWfService] not found; Component will fail
24.08.2016 22:04:19.747 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(3816)] bind method [bindWfService] not found; Component will fail
24.08.2016 22:04:19.748 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(3816)] bind method [bindRcManager] not found; Component will fail
24.08.2016 22:04:19.748 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(3816)] bind method [bindWcmWfService] not found
24.08.2016 22:04:19.748 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(3816)] bind method [bindWfService] not found
24.08.2016 22:04:19.748 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(3816)] bind method [bindRcManager] not found
24.08.2016 22:04:19.755 *INFO* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle Service [com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess,7286, [com.day.cq.workflow.exec.WorkflowProcess]] ServiceEvent REGISTERED
24.08.2016 22:04:19.756 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(3817)] bind method [bindWcmWfService] not found; Component will fail
24.08.2016 22:04:19.757 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(3817)] bind method [bindWfService] not found; Component will fail
24.08.2016 22:04:19.757 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(3817)] bind method [bindRcManager] not found; Component will fail
24.08.2016 22:04:19.757 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(3817)] bind method [bindWcmWfService] not found
24.08.2016 22:04:19.758 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(3817)] bind method [bindWfService] not found
24.08.2016 22:04:19.758 *ERROR* [qtp782094611-821] com.adobe.acs.acs-aem-commons-bundle [com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(3817)] bind method [bindRcManager] not found
```

I downloaded the acs-aem-commons-content-2.6.6-min.zip from the below page and installed it using package manager.

  https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases

Environments:
- ACS AEM Commons Version : 2.1.2
- AEM 6.1 SP1

**Comment by joerghoh** [comment] 2016-09-07 09:55
I can confirm this for AEM 6.0 as well

**Comment by KiranVedantam** [comment] 2016-12-01 10:46
Hi, 
Anyone knows how to solve this error. I am facing the same issue in my project. The code of project is in 5.6 and migrated to 6.1 and using the latest acs-commons pacakge (2.8.0). 

Thanks in advance.

**Comment by justinedelson** [comment] 2016-12-01 15:57
Does this manifest itself in any way other than the log messages? i.e. are those workflow processes actually non-functional? I don't think this issue is particularly simple to address on the 6.0/6.1 branch.

**Comment by KiranVedantam** [comment] 2016-12-05 08:37
@justinedelson, i am not sure about which workflow you were mentioning. I have checked in the workflow management for the below workflows and i am not able to find them. Can you please let me know about those in detail?

Workflows:
com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess
com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess

**Comment by justinedelson** [comment] 2016-12-05 15:09
@KiranVedantam I was referring to the workflow processes in the error message. What kind of details are you looking for?

**Comment by KiranVedantam** [comment] 2016-12-07 04:06
@justinedelson I am wanting to know why is the error visible in the log files. Can we ignore this? until and unless we leverage ParameterizedActivatePageProcess related workflow I feel it will not impact your implementation. Am I right?

**Comment by royteeuwen** [comment] 2017-01-19 23:11
I would also like to have an answer on this one, having the same problems on an AEM 6.1 SP2

**Comment by davidjgonzalez** [comment] 2017-01-20 00:11
@royteeuwen is this happening on a "vanilla" 6.1 + SP2? Are you installing anything else?

**Comment by royteeuwen** [comment] 2017-01-21 12:29
Hey @davidjgonzalez ,

I just started a new aem 6.1 quickstart jar, installed SP2 and then CFP4 and then the acs-aem-commons-content 2.9.0 and yup,  I still get the following error:

```
[com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(2272)] bind method [bindWcmWfService] not found; Component will fail
[com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(2272)] bind method [bindWfService] not found; Component will fail
[com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(2272)] bind method [bindRcManager] not found; Component will fail
[com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(2272)] bind method [bindWcmWfService] not found
[com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(2272)] bind method [bindWfService] not found
[com.adobe.acs.commons.workflow.process.impl.ParameterizedDeactivatePageProcess(2272)] bind method [bindRcManager] not found
[com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(2304)] bind method [bindWcmWfService] not found; Component will fail
[com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(2304)] bind method [bindWfService] not found; Component will fail
[com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(2304)] bind method [bindRcManager] not found; Component will fail
[com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(2304)] bind method [bindWcmWfService] not found
[com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(2304)] bind method [bindWfService] not found
[com.adobe.acs.commons.workflow.process.impl.ParameterizedActivatePageProcess(2304)] bind method [bindRcManager] not found
```

Greets,
Roy

**Comment by justinedelson** [comment] 2017-01-21 13:36
My initial analysis is that this issue is not fixable without entirely rewriting these components. Note - this problem is specific to 6.1. It does not happen with the 6.2 branch.

**Comment by royteeuwen** [comment] 2017-01-21 13:38
Hey Justin,

Ok no problem, can you clarify why this is resolved in AEM 6.2? What is causing the issue?

Greets
Roy

**Comment by justinedelson** [comment] 2017-01-21 13:42
The problem is that these components extend SCR components from AEM and the injected references into the base components changed between 6.0 and 6.1. The `master` branch of this project is built against the 6.0 UberJar, so it only knows about the injected references from 6.0.

For the 6.2 branch, we build against the 6.2 UberJar, so this is not an issue there. As far as I can tell, this will not be an issue for 6.3 either.

Long term, if our objective is to be cross-compatible between releases we should probably get rid of all cases where SCR components are extended since the injected references are not currently considered to be part of the API and so are free to change between releases (or even service packs/CFPs).

**Comment by davidjgonzalez** [comment] 2017-01-21 13:44
i assume the problem comes from extending the OOTB De/ActivatePageProcesses?

Would a simple fix me to swap out 

`super.execute(workItem, workflowSession, args);`

with 

```
@Reference(target=<pid>)
private WorkflowProcess workflowProcess;
...
workflowProcess.execute(workItem, workflowSession, args);
``` 

Seems like a simple fix?

**Comment by royteeuwen** [comment] 2017-01-21 13:51
That does indeed look like a simple temp solution for the AEM 6.1 branch :). And indeed, extending an OOTB component maybe should be avoided

**Comment by davidjgonzalez** [comment] 2017-01-21 15:41
Oh - i guess that won't work..  the problem being:

```
   @Override
    protected ReplicationOptions prepareOptions(ReplicationOptions opts) {
```

**Comment by justinedelson** [comment] 2017-01-21 17:08
@davidjgonzalez I don't think that will work. The whole point is to be able to customize the agent filter which gets created inside the execute method of the base class.

**Comment by davidjgonzalez** [comment] 2017-01-21 17:21
Yup .. ^^^

**Comment by royteeuwen** [comment] 2017-01-21 17:37
Okey no problem, I'll wait another 2 months for the upgrade to 6.2 ;).

**Comment by ssga-aem** [comment] 2017-08-23 18:53
Is it okay to ignore the bind/unbind error if we are using AEM 6.1 and can still use ACS commons on a PROD instance? We are planning to upgrade to 6.3 early next year, but want to use ACS commons in PROD in meantime.

**Comment by justinedelson** [comment] 2017-08-23 18:58
@ssga-aem as far as I know, this only impacts these two components. If you don't use them (and you apparently can't on 6.1), then it doesn't affect you.

**Comment by justinedelson** [comment] 2017-08-23 18:58
I hate to do this because this is an annoying bug, but I'm making this as wontfix and closing it. If someone wants to come up with a clever solution which works across 6.0 & 6.1, please reopen.

**Closed by justinedelson** 2017-08-23 18:58 UTC
Labels: bug, help wanted, wontfix
