### ISSUE TITLE
Build breaking with unit test issues

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/acs-aem-commons#1732] opened 2019-01-29 21:55 UTC
The following tests are not passing:

HealthCheckStatusEmailerTest:
- [ ] run_WithoutFailuresSendEmail
- [ ] run_WithFailuresSendEmail
- [ ] run_WithFailuresSendEmail_2
- [ ] throttledExecution

CaffeineMemHttpCacheStoreImplTest:
- [ ] test_addCacheData

MemHttpCacheStoreImplTest:
- [ ] test_addCacheData

EnsureOakIndexJobHandlerTest:
- [ ] Exception in setup method affecting all tests

EnsureOakIndexManagerImplTest:
- [ ] testWithIndexRegistrations

AemEnvironmentIndicatorFilterTest:
- [ ] testAcceptForReferrers
- [ ] testFiltering
- [ ] testAllowedWcmMode
- [ ] testAcceptForXRequestedWithHeader
- [ ] testAcceptForMethod

ComponentErrorHandlerImplTest:
- [ ] testAccepts_suppressResourceTypes

CQIncludePropertyNamespaceServletTest:
- [ ] testNamePropertyUpdater_MultiLevel
- [ ] testNamePropertyUpdater_PropertyNames

![image](https://user-images.githubusercontent.com/5144198/51942719-67ef6e80-23dd-11e9-95d4-9f349999651f.png)

**Comment by joerghoh** [comment] 2019-01-31 21:02
Testing on my machine the build starts to fail with commit b90d184e81bf0203bd15c5162ca024719ccc948c by @kwin (#1714). The previous commit 881567c538662278e04afe7c1dbda8e5e37079e3 seems to build fine. Supported by the travis build logs:
* [build 3765](https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/builds/481386978) is working fine
* [build 3766](https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/builds/481521490) fails

The analysis for the failing Unittest for `ÈnsureOakIndexManagerImpl`` on master revealed these finding:
* The properties are not passed properly down to the EnsureOakIndex component, thus the "ensure-definitions.path" was always blank triggering the RuntimeException.
* steppting into the MockOsgi stuff with the debugger I found that the component property for `ÈnsureOakIndex`` map only contained the ``webconsole.configurationFactory.nameHint`` property.
* In ``target/classes/OSGI-INF/com.adobe.acs.commons.oak.impl.EnsureOakIndex.xml`` I only found this nameHint property, but not the other properties (like ``ensure-definitions.path``).
* But I found these properties in ``target/classes/OSGI-INF/metatype/com.adobe.acs.commons.oak.impl.EnsureOakIndex\$Config.xml``
* Using the debugger I found https://github.com/apache/sling-org-apache-sling-testing-osgi-mock/blob/master/core/src/main/java/org/apache/sling/testing/mock/osgi/OsgiMetadataUtil.java#L156 which reads all available SCR metadata from the OSGI-INF directory, but ignores all metatype files.

For that reason I believe that we cannot fix ACS AEM Commons here without switching back to a combination of plugins, which create the full set of properties also in the scr XML files. And additionally I would suggest that the Sling OSGI Mocks should be extended to deal with this combination of SCR and metatype files.

@kwin Does my theory sound resonable?

**Comment by kwin** [comment] 2019-02-01 05:48
On my local machine building master works totally fine
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/jre
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"
```

The file `target/classes/OSGI-INF/com.adobe.acs.commons.oak.impl.EnsureOakIndex.xml` looks like this for me
```
<?xml version="1.0" encoding="UTF-8"?>
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.3.0" name="com.adobe.acs.commons.oak.impl.EnsureOakIndex" configuration-policy="require" activate="activate">
  <property name="webconsole.configurationFactory.nameHint" type="String" value="Definitions: {ensure-definitions.path}, Indexes: {oak-indexes.path}"/>
  <service>
    <provide interface="com.adobe.acs.commons.oak.impl.AppliableEnsureOakIndex"/>
  </service>
  <reference name="checksumGenerator" interface="com.adobe.acs.commons.analysis.jcrchecksum.ChecksumGenerator" field="checksumGenerator"/>
  <reference name="resourceResolverFactory" interface="org.apache.sling.api.resource.ResourceResolverFactory" field="resourceResolverFactory"/>
  <reference name="scheduler" interface="org.apache.sling.commons.scheduler.Scheduler" field="scheduler"/>
  <implementation class="com.adobe.acs.commons.oak.impl.EnsureOakIndex"/>
</scr:component>
```
@joerghoh Obviously in your case the XML file only contains the property directly added via the `@Component` annotation (https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/20bb419ac832a8be675593cf4b623df8b3b769bd/bundle/src/main/java/com/adobe/acs/commons/oak/impl/EnsureOakIndex.java#L49), but not the ones being added indirectly via the component property type. Both are supposed to be merged by bnd! This seems like a bug in either bnd or the underlying maven-bundle-plugin. For sure the properties are only supposed to be read from SCR metadata (the metatype does not matter here at all, so OSGi Mock is correct).

Do you see any output from `maven-bundle-plugin` which would explain that behaviour?

**Comment by kwin** [comment] 2019-02-01 06:03
I had a closer look at the travis log files and observed the following in https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/jobs/481521491#L3361.

It does not execute maven-bundle-plugin prior to executing the tests, i.e. generate-scr-metadata-for-unittests is missing.

**Comment by kwin** [comment] 2019-02-01 06:17
I assume that something is wrong with the classpath for bnd in travis during maven-bundle-plugin:4.1.0:manifest (generate-scr-metadata-for-unittests) (https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/jobs/487222463#L3808). It emits the following warnings
```
[INFO] Unable to determine whether the meta annotation org.osgi.service.component.annotations.ComponentPropertyType applied to type com.adobe.acs.commons.audit_log_search.impl.AuditLogSearchServlet provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.checkerframework.checker.nullness.qual.Nullable applied to type com.google.common.base.Absent provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.errorprone.annotations.CanIgnoreReturnValue applied to type com.google.common.base.AbstractIterator provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.errorprone.annotations.concurrent.LazyInit applied to type com.google.common.base.Converter provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation org.checkerframework.checker.nullness.qual.MonotonicNonNull applied to type com.google.common.base.Converter provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.errorprone.annotations.ForOverride applied to type com.google.common.base.Converter provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.errorprone.annotations.CheckReturnValue applied to type com.google.common.base.package-info provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.errorprone.annotations.CompatibleWith applied to type com.google.common.cache.Cache provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.j2objc.annotations.Weak applied to type com.google.common.cache.LocalCache$AbstractCacheSet provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.errorprone.annotations.concurrent.GuardedBy applied to type com.google.common.cache.LocalCache$Segment provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.j2objc.annotations.RetainedWith applied to type com.google.common.collect.AbstractBiMap provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.errorprone.annotations.Immutable applied to type com.google.common.collect.DenseImmutableTable provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.errorprone.annotations.MustBeClosed applied to type com.google.common.io.CharSource provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.j2objc.annotations.ReflectionSupport applied to type com.google.common.util.concurrent.AbstractFuture provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[INFO] Unable to determine whether the meta annotation com.google.errorprone.annotations.OverridingMethodsMustInvokeSuper applied to type com.google.common.util.concurrent.AggregateFuture$RunningState provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.wcm.core.contentfinder.ContentFinderListInfoProviderHelper is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Reference applied to type com.day.cq.wcm.core.contentfinder.ContentFinderListInfoProviderHelper is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Reference applied to type com.day.cq.commons.servlets.AbstractPredicateServlet is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.commons.servlets.AbstractPredicateServlet is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Activate applied to type com.adobe.cq.dialogconversion.AbstractDialogRewriteRule is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.adobe.cq.dialogconversion.AbstractDialogRewriteRule is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.wcm.workflow.process.ActivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Service applied to type com.day.cq.wcm.workflow.process.ActivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Property applied to type com.day.cq.wcm.workflow.process.ActivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Reference applied to type com.day.cq.wcm.workflow.process.ReplicatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.wcm.workflow.process.ReplicatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Component applied to type com.day.cq.wcm.workflow.process.DeactivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Service applied to type com.day.cq.wcm.workflow.process.DeactivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Unable to determine whether the annotation org.apache.felix.scr.annotations.Property applied to type com.day.cq.wcm.workflow.process.DeactivatePageProcess is a component property type as it is not on the project build path. If this annotation is a component property type then it must be present on the build path in order to be processed
[WARNING] Manifest com.adobe.acs:acs-aem-commons-bundle:bundle:3.19.1-SNAPSHOT : Export com.adobe.acs.commons.mcp.model,  has 1,  private references [com.adobe.acs.commons.mcp.model.impl]
```

On my local machine I see the same amount of INFOs/WARNINGs but all tests succeed, though.

The problem is that there is certainly a lot of noise which can safely be disregarded (compare also with https://github.com/bndtools/bnd/issues/2772) so it is hard to see the actual issue here.

**Comment by joerghoh** [comment] 2019-02-01 06:59
@kwin I see these messages as well and IIRC we have them since we use maven-bundle-plugin 4.1.0, and we had succesfull builds with them also on Travis.

**Comment by kwin** [comment] 2019-02-01 11:03
One issue is definitely that we extend from components which still have Felix SCR annotations, e.g. in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/a4ad6c31263588286cb5380a3919675a64707e1c/bundle/src/main/java/com/adobe/acs/commons/workflow/process/impl/ParameterizedActivatePageProcess.java#L38. Most probably we have to bring bnd to ignoring those parents!

**Comment by joerghoh** [comment] 2019-02-01 20:55
ok, just saw the response on https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1732#issuecomment-459614123

Yes, that's the XML file looks like. And if it's the case on your side as well, I wonder how the testcase passes on your machine.

**Comment by badvision** [comment] 2019-02-01 21:15
Ah yes I see those warnings @kwin -- I think that we have to include the SCR library in the build path because we extend classes which still use those elsewhere in the product, but we just don't want to use them ourselves here.

**Comment by kwin** [comment] 2019-02-02 17:04
@joerghoh Actually the component metadata for EnsureOakIndex is 100% correct. OSGi R7 Comp, Chapter 112.8.2  states 
> Component property types can be used in two ways:
• Component property types can be used to annotate the component implementation class, along side the Component annotation. The annotation usage can specify property values which can be different than the default values declared in the component property type.
To be used in this way, the component property type must be annotated with the Component- PropertyType meta-annotation so that, at build time, the annotation is recognized as a compo- nent property type.
• Component property types can be used as parameter types in the component's constructor and life cycle methods, or as field types for activation fields. The component implementation can use objects of a component property type at runtime to access component property values in a type safe manner.
To be used in this way, it is recommended the component property type be annotated with the ComponentPropertyType meta-annotation but it is not required.

Actually https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/20bb419ac832a8be675593cf4b623df8b3b769bd/bundle/src/main/java/com/adobe/acs/commons/oak/impl/EnsureOakIndex.java#L65 is no(!) component property type, therefore only the directly used property is ending up in the component metadata. Only the metatype annotations from the config class are relevant.

Regarding the unit test of `EnsureOakIndexJobHandler` which fails in Travis e.g. in https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/jobs/487691186#L4469 with java.lang.RuntimeException: Unable to invoke method 'activate' for class com.adobe.acs.commons.oak.impl.EnsureOakIndex
	at com.adobe.acs.commons.oak.impl.EnsureOakIndexJobHandlerTest.setup(EnsureOakIndexJobHandlerTest.java:102)
Caused by: java.lang.IllegalArgumentException: OSGi Configuration Property `ensure-definitions.path` cannot be blank.
	at com.adobe.acs.commons.oak.impl.EnsureOakIndexJobHandlerTest.setup(EnsureOakIndexJobHandlerTest.java:102):

I don't see how the property with that name cannot be set, as we are explicitly calling the right property value in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/fa1b92d257b308a22382c643fd9f6613e84fd6d7/bundle/src/test/java/com/adobe/acs/commons/oak/impl/EnsureOakIndexJobHandlerTest.java#L96. 

As I still cannot reproduce locally I am wondering if this is related somehow to the order in which tests are being executed. 

@joerghoh Can you try executing with `mvn clean verify -Dsurefire.runOrder=alphabetical`

**Comment by adamcin** [comment] 2019-02-03 13:32
@joerghoh is that sling issue you created possibly a duplicate of SLING-8244?

**Comment by joerghoh** [comment] 2019-02-03 15:31
@adamcin yepp, indeed. Haven't seen your ticket. Will mark it as duplicate.

**Comment by joerghoh** [comment] 2019-02-03 19:16
For the records: In unittests the translation of the $_$ to "-" is not working only for the user the class with the  @ObjectClassDefinition annotation, thus reading the properties from it in the `activate()`` method only results in the defaults.

The workaround is not to use the configuration class, but use the "traditional" way of reading component properties. This can be achieved in this case (yes, it's supported!):

```
@ObjectClassDefinition(...)
public @interface Config {
  @AttributeDefinition (...)
  String my_param() default "bla";
}

@Activate
procted void activate (Config config, Map<String,Object> params) {
  String myparam = config.my_param();
  String anotherParam = PropertiesUtil.getString(params.get("another-param"),"default");
}
```

**Comment by niekraaijmakers** [comment] 2019-02-04 13:16
I checked the Caffeine and Mem cache, they didn't fail for me locally with the latest master branch. Is this still the case?

**Comment by adamcin** [comment] 2019-02-04 19:02
@joerghoh just to clarify, merely using `$_$` in tooling that supports the R7 annotations will bump the metatype xmlns to v1.4.0, which is not supported in any AEM 6.4 service pack. So even after getting the unit tests to pass with `$_$` properties, those services will not be configurable in the Felix Web Console

**Comment by davidjgonzalez** [comment] 2019-02-08 16:04
Closing as we are moving back to SCR annotations: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1741

**Closed by davidjgonzalez** 2019-02-08 16:04 UTC
Labels: help wanted
