### ISSUE TITLE
com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl: Error while saving changes: javax.jcr.RepositoryException: Error during assembly of /etc/designs/rwjf/clientlibs/public.js. reverting.

### ISSUE THREAD

**Issue by mansiagg1101** [Adobe-Consulting-Services/acs-aem-commons#1491] opened 2018-09-21 15:13 UTC
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _6.4_____
* [x] ACS AEM Commons Version: __3.17.4___
* [x] Reproducible on Latest?  YES

### Expected Behavior

_Please describe briefly the expected behavior, i.e. when I do X, Y should happen._

I am working on Local-publish environment. When I loaded my site and pressed F12,  I noticed that public.min.js was not getting created. 
![image](https://user-images.githubusercontent.com/33690423/45889361-41198f80-bd8e-11e8-8845-951b8f68b41c.png)

### Actual Behavior
public.js should be created without min in the file name.

### Steps to Reproduce
Run your local instance with publish in AEM 6.4.
Load your website and press f12, Public..timestamp.js is not created with server is looking for new name i.e public.min.timestamp.js.

Errors in the log file
**
![image](https://user-images.githubusercontent.com/33690423/45889797-50e5a380-bd8f-11e8-8dd1-bce07c1db2a4.png)
**

### Links

_Links to related assets, e.g. content packages containing test components_

**Comment by justinedelson** [comment] 2018-09-21 16:30
What leads you to believe this is related to ACS AEM Commons? The "min" selector is added by the OOTB client library system.

And that's obviously a custom client library which has invalid JavaScript (`abstract` is a reserved word in JavaScript).

**Comment by mansiagg1101** [comment] 2018-09-21 16:32
Yeah My Bad, I raised issue in wrong place. Can you suggest me the right place for this issue?

**Comment by justinedelson** [comment] 2018-09-21 16:53
TBH, I'm not sure there is an issue here, but...

* If the issue is that minification is disabled in the client library manager but the min selector is still getting added, that's an issue for AEM product support. And it would be super weird. But weird stuff happens all the time. And I do see that you appear to be using the ACS AEM Commons Versioned ClientLibs Transformer (that what adds the numbers after the "min"). This shouldn't change the minification state (the transformer just reads it from the client library manager). But to be on the safe side you may want to disable this to better isolate the problem.
* The invalid JavaScript is an issue for whomever wrote this client library.

**Comment by mansiagg1101** [comment] 2018-09-21 17:17
Yes, There are some errors in client library of  YUIScriptProcessor. See the attached log file. Do you know where I can raise this issue?

**Comment by davidjgonzalez** [comment] 2018-09-22 02:14
Closing this issue as it doesn't relate to ACS Commons project. To resolve this, as JE mentions, you need to figure out who wrote that code, and then work them to fix it.

**Closed by davidjgonzalez** 2018-09-22 02:14 UTC
