### ISSUE TITLE
Multifield not working when AEM is upgraded from 6.3 to 6.5 , we have used latest acs-aem-commons 4.0.0

### ISSUE THREAD

**Issue by bhaveshkaloni** [Adobe-Consulting-Services/acs-aem-commons#2008] opened 2019-07-30 07:22 UTC
AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM 6.5
  ACS AEM Commons Version: 4.1.0
  Reproducible on Latest? Yes
Expected Behavior
On saving the multifield dialog the values should persist.

Actual Behavior
On saving the multifield dialog the values does not persist.

**Comment by FireFoxG** [comment] 2019-08-29 07:26
We faced this issue ourselves and I think I found what is the cause of it.
Multifield values are being handled by additional JS that comes from /apps/acs-commons/touchui-widgets/composite-multifield
All touchui-widgets are injected in AEM's clientlibs via category cq.authoring.dialog, which was always set on **/apps/acs-commons/touchui-widgets** clientlib folder.
This worked up until ACS AEM Commons 3.18.2, but starting from version 4.0.0, touchui-widgets has become just an nt:folder, instead of cq:ClientLibraryFolder.

The solution for now is to install 3.18.2 first and then 4.1.0, or change this node (/apps/acs-commons/touchui-widgets) manually.

Here are the values from 3.18.2
jcr:primaryType="cq:ClientLibraryFolder"
          jsProcessor="[default:none,min:gcc]"
          categories="[cq.authoring.dialog,acs-commons.cq.authoring.dialog,granite.ui.coral.foundation.addon.coral2,acs-commons.granite.ui.coral.foundation.addon.coral2]"
    dependencies="[underscore,acs-commons.granite.ui.coral2.foundation,acs-commons.jquery.fonticonpicker,acs-commons.fontawesome]"

**Comment by joerghoh** [comment] 2019-10-28 08:27
According to [1], the multified widgets have been deprecated in favor of the Granite UI Multifield. And there is also the description how to enable the ACS AEM Commons version of the multifields again.

For me this is working as intended.
@FireFoxG can you confirm and then close this issue?


[1] https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/multifield-extension/index.html

**Closed** 2020-01-03 09:48 UTC
Labels: wontfix
