### ISSUE TITLE
Unable to drag and drop the component from sidekick in AEM 6.4 using classic UI. classicui-limit-parsys.js limit is undefined.

### ISSUE THREAD

**Issue by lokeshvajrala** [Adobe-Consulting-Services/acs-aem-commons#1759] opened 2019-02-19 18:43 UTC
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.2
* [ ] ACS AEM Commons Version: 3.17.4
* [ ] Reproducible on Latest? yes

### Expected Behavior

Should be able to drag & drop the components from sidekick on to the parsys.

### Actual Behavior

Drag & drop the component from the sidekick to the pasrys isn't working in classic UI and there is console error from this file https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/widgets/configure-limit-parsys/classicui-limit-parsys.js#L96. 
It looks like sometimes the "designObject" is not initialized within the pageInfo and just returns as an undefined limit object.
![image](https://user-images.githubusercontent.com/41201017/53039038-6a247600-343b-11e9-8be8-b5c3d0c382de.png)

### Steps to Reproduce

1. Start AEM 6.4.2
2. Install ACS commons 3.17.4 or the latest.
3. Install the attached content package.
4. Open the page http://localhost:4502/content/parsys-drag-drop-issue.html
5. Drag & drop the component to the parsys to see the console error. Some times it works, so try refreshing the window or try in the incognito window.

[classicUI-drag-drop-issue-0.1.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2881468/classicUI-drag-drop-issue-0.1.zip)

**Comment by kwin** [comment] 2019-02-28 19:37
Isn't this a duplicate of https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1516?
@lokeshvajrala Can you try either 3.19.0 or newer?

**Comment by davidjgonzalez** [comment] 2019-03-13 18:19
Closing as a dupe of #1516 as @kwin mentions. Please re-open if this turns out it is not a duplicate and still exists in 3.19.0+.

**Comment by lokeshvajrala** [comment] 2019-03-14 01:20
@kwin, @davidjgonzalez Tested with the latest version (4.0.0), it seems like the issue still exists. The problem is with the limit object at https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/content/src/main/content/jcr_root/apps/acs-commons/widgets/configure-limit-parsys/classicui-limit-parsys.js#L96. as it is undefined sometimes due to the undefined "pageInfo.designObject " at #L55. Also, created a PR to resolve the issue - https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1787

Content package to reproduce the issue: 
[classicUI-drag-drop-issue-0.2.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/2964278/classicUI-drag-drop-issue-0.2.zip)

**Comment by anand19cse** [comment] 2019-06-12 08:53
Is this issue fixed?
I tried with latest version of ACS (4.1.0) and issues still exists.
We are also getting same error on all environment including prod. And business is not able to drag and drop any component in parsys.
Could you please fix it as soon as possible? It is very critical issue for editors.

**Comment by davidjgonzalez** [comment] 2019-06-12 14:03
@anand19cse are you explicitly including the ACS Commons classicUI Widgets clientlibs? Or in other words, are you trying to use this feature? Or is this appearing simply because ACS AEM Commons is installed?

**Closed** 2019-06-12 14:04 UTC
Labels: bug, duplicate
