### ISSUE TITLE
Shared Component Properties do not work in AEM 6.5

### ISSUE THREAD

**Issue by reggie7** [Adobe-Consulting-Services/acs-aem-commons#1858] opened 2019-04-25 10:49 UTC
* [ ] AEM Version: `6.5`
* [ ] ACS AEM Commons Version: `4.0.0`
* [ ] Reproducible on Latest? yes

### Expected Behavior

[Shared Component Properties](https://adobe-consulting-services.github.io/acs-aem-commons/features/shared-component-properties/index.html) works properly in `AEM 6.5`.

### Actual Behavior

[Shared Component Properties](https://adobe-consulting-services.github.io/acs-aem-commons/features/shared-component-properties/index.html) does not work properly in `AEM 6.5`:

- *Shared Properties* dialog does not open at all.
- *Global Properties* dialog does not open at all.
- *Configure* dialog does not open after clicking an icon for one of the above mentioned dialogs.

### Steps to Reproduce

1. Follow [How to use](https://adobe-consulting-services.github.io/acs-aem-commons/features/shared-component-properties/index.html#how-to-use) steps,
2. Remember that `com.adobe.acs.commons.wcm.impl.PageRootProviderImpl` is actually [wrong](https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/156/files) - use `com.adobe.acs.commons.wcm.impl.PageRootProviderConfig` instead,
3. Create an example page for yourself where you'd get something like this:

![shared-global-example](https://user-images.githubusercontent.com/5563546/56730025-07ab6700-6757-11e9-839b-6466f6794ca5.png)

4. Click the first icon - it should work,
5. Click the second icon - it does not work,
6. Click the third icon - it does not work,
7. Click the first icon again - it does not work anymore.

**Comment by davidjgonzalez** [comment] 2019-04-26 02:38
@HitmanInWis have you had a chance to try SCP's out in AEM 6.5 yet? 

+1 on the documentation update though..

**Comment by HitmanInWis** [comment] 2019-04-29 12:37
I've not yet tested SCP on AEM 6.5.  I'll see if I can take a look this week to at least gauge the effort to fix.  And yes, I should also get that documentation of `PageRootProviderConfig` updated...

**Comment by reggie7** [comment] 2019-04-29 14:17
@HitmanInWis - please note this [PR](https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/156/files) though, it should be enough for the docs maybe?

**Comment by HitmanInWis** [comment] 2019-04-29 17:41
Thank you @reggie7 for banging out that documentation update!  That is merged now.

**Comment by HitmanInWis** [comment] 2019-04-29 20:54
I just tested Shared Component Properties (SCP) out on AEM 6.5 and it's working just fine for me.  It's possible that the problem is only with the example package, since that was created quite possibly on AEM 6.1...

**Comment by HitmanInWis** [comment] 2019-04-29 21:23
Found the issue, and turns out the effect is largely just the example package.  However, if someone implemented SCP by copying code from the example package then I guess it would affect them as well.

Back in AEM 6.1 a workaround was needed where SCP dialogs needed to use a special "acs-commons/gui/components/authoring/dialogshared" type to prevent a NPE for the dialog when the node storing the content did not yet exist, but this has not been necessary since AEM 6.2.  I think because SCP officially went live in ACS Commons when 6.2 was the main AEM version we never even included this in documentation.  Dialogs using the OOTB sling:resourceType of `cq/gui/components/authoring/dialog` work just fine.

Apparently on AEM 6.5 the custom resource type in ACS Commons is no longer working.  Ideally we'd just delete this old resource type from ACS Commons as it is absolutely not necessary and truly should be avoided to prevent future compatibility issues.  However, given the chance that someone *might* be using that old ACS Commons resourceType (even with it not being officially documented) I'm wondering if we instead need to update that resourceType to work on 6.5 (probably just remove all of the custom code and have it descend from the default type).

**Comment by HitmanInWis** [comment] 2019-04-29 22:38
Fixed the issue for sake of backward compatibility (see above PR).

**Closed by HitmanInWis** 2019-04-29 22:38 UTC
Labels: undocumented

**Comment by reggie7** [comment] 2019-05-06 11:06
Just checked it and it indeed works with the new example package. Thank you, @HitmanInWis

**Comment by nafeespeer** [comment] 2019-09-18 19:57
Hi @reggie7 and @HitmanInWis  - Could you please provide me the latest documentation to make this feature work in AEM 6.5? 

I am not able to find those nodes mentioned in the documentation in AEM 6.5 for "Adding the Page Info Provider to your Page Component".  Any help here would be appreciated?

**Comment by HitmanInWis** [comment] 2019-09-18 21:38
you need to find your base page component - it might not already have a `cq:infoProviders` node and if it doesnt then you'll have to add one.  If you find the base page component under /libs in AEM you can see the default version of the `cq:infoProviders` node.
