### ISSUE TITLE
Versioning of clientlibs fails on 6.3 author

### ISSUE THREAD

**Issue by sivaisukapalli** [Adobe-Consulting-Services/acs-aem-commons#1186] opened 2017-11-27 21:10 UTC
When we enable versioning on 6.3 author, we are able to see the clientlibs appended with md5. But if we try to edit any component, the overlay edit dialog doesn't close and throws a javascript console error ( can't clear history).

**Comment by araraty** [comment] 2017-11-28 07:30
Hey Siva
Is this 6.3 with no Hotfix or Service Pack?
What version of ACS did you install?

**Comment by sivaisukapalli** [comment] 2017-11-28 15:13
it's 6.3.0 without any SP. 
And ACS 3.11.0

**Comment by justinedelson** [comment] 2017-11-28 15:26
I cannot reproduce this with 6.3 GA and ACS Commons 3.12.0.

Please provide the precise steps to reproduce and the exact error message seen.

**Comment by sivaisukapalli** [comment] 2017-11-28 17:08
this is the error I get. 
core.min.js:21709 Uncaught TypeError: Cannot read property 'clear' of null
    at ns.edit.Dialog.onSuccess (core.min.js:21709)
    at execute (core.min.js:20817)
    at HTMLDocument.handleDialogSuccess (core.min.js:20794)
    at HTMLDocument.dispatch (jquery.min.ACSHASHfb50358df4c2bd6aa6e1dd5b0d9b9d29.js:103)
    at HTMLDocument.k.handle (jquery.min.ACSHASHfb50358df4c2bd6aa6e1dd5b0d9b9d29.js:96)
    at Object.trigger (jquery.min.ACSHASHfb50358df4c2bd6aa6e1dd5b0d9b9d29.js:101)
    at HTMLDocument.<anonymous> (jquery.min.ACSHASHfb50358df4c2bd6aa6e1dd5b0d9b9d29.js:115)
    at Function.each (jquery.min.ACSHASHfb50358df4c2bd6aa6e1dd5b0d9b9d29.js:28)
    at c.fn.init.each (jquery.min.ACSHASHfb50358df4c2bd6aa6e1dd5b0d9b9d29.js:24)
    at c.fn.init.trigger (jquery.min.ACSHASHfb50358df4c2bd6aa6e1dd5b0d9b9d29.js:115)
ns.edit.Dialog.onSuccess @ core.min.js:21709
execute @ core.min.js:20817

Steps to follow are

1) Install 3.11 ( or 3.12 of ACS commons) 
2) create a node of rewrite 
Used the default node (/libs/cq/config/rewriter/default) to create http://localhost:4502/apps/XXXX/config/rewriter/versioned-clientlibs following is the json. md5 is being added but edit functionality is broken.
( http://localhost:4502/apps/XXXX/config/rewriter/versioned-clientlibs.json)  
{
"jcr:primaryType": "nt:unstructured",
"enabled": true,
"serializerType": "htmlwriter",
"transformerTypes": [
"linkchecker",
"versioned-clientlibs"
],
"order": "1",
"contentTypes": [
"text/html"
],
"generatorType": "htmlparser"
}

**Comment by justinedelson** [comment] 2017-11-28 17:19
There must be other steps you have done. This shows that minimization and MD5 enforcement have been enabled. It is also odd that you would see a line number of 21709 (or 20817) on core.min.js. This file is about 8500 lines minified. And it is obviously odd that this JavaScript request doesn't have the md5 in it.

Please start with a clean 6.3 instance and provide the full steps to reproduce.

**Comment by sivaisukapalli** [comment] 2017-11-28 18:19
Thank you. Just checked a clean instance, doesn't have this issue.  Have to figure out what in our code is causing this issue. Will look into it. Thanks.

**Comment by justinedelson** [comment] 2017-11-28 18:49
ok. I'm going to close this. feel free to reopen if you figure out if it is an issue.

**Closed by justinedelson** 2017-11-28 18:49 UTC
